import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";

const ROOT = fileURLToPath(new URL("..", import.meta.url));

test("Command Center asset is a dark, visual, responsive workstation with honest states", async () => {
  const html = await readFile(`${ROOT}/workspace.html`, "utf8");
  const dealHtml = await readFile(`${ROOT}/index.html`, "utf8");
  const css = await readFile(`${ROOT}/css/workspace.css`, "utf8");
  const js = await readFile(`${ROOT}/js/workspace-command-center.js`, "utf8");
  const modelJs = await readFile(`${ROOT}/js/workspace-command-center-model.js`, "utf8");
  const dealJs = await readFile(`${ROOT}/js/app.js`, "utf8");
  const surfaces = await Promise.all(["leads.html", "queue.html", "room.html", "system-work.html"].map((file) => readFile(`${ROOT}/${file}`, "utf8")));
  assert.match(html, /id="commandCenterVisual"/);
  assert.match(html, /aria-live="polite"/);
  assert.match(html, /href="\/leads"/);
  assert.match(html, /href="\/deals/);
  assert.match(html, />CALLS</);
  assert.match(html, /href="\/system-work\.html"/);
  assert.match(html, /href="\/room\.html"/);
  assert.match(css, /--ink-0:#0/);
  assert.match(css, /backdrop-filter/);
  assert.match(css, /@media\s*\(prefers-reduced-motion:reduce\)/);
  assert.match(css, /pulse-attention/);
  assert.match(js, /\/api\/v1\/command-center/);
  assert.doesNotMatch(js, /api\/v1\/workspace\/command-center/);
  assert.match(js, /AUTHENTICATION_REQUIRED/);
  assert.match(js, /observed_at/);
  assert.match(js, /source\.freshness/);
  assert.match(js, /\.catch/);
  assert.doesNotMatch(html, /System online/);
  assert.match(html, /Checking workspace/);
  assert.doesNotMatch(html, /pulse-attention[^>]+href="\/system-work\.html"/);
  assert.match(html, /System state/);
  assert.match(modelJs, /valid_until/);
  assert.match(modelJs, /owned_flagged_deals/);
  assert.match(modelJs, /state: "unavailable"/);
  assert.match(dealHtml, /data-filter="flagged"/);
  assert.match(dealJs, /deal\.attention === true/);
  assert.match(dealJs, /params\.get\('owner'\) === 'me'/);
  assert.match(html, /class="mobile-nav"/);
  assert.match(html, />Home</);
  assert.match(html, />Leads</);
  assert.match(html, />Deals</);
  assert.match(html, />System</);
  assert.match(html, />Observe</);
  assert.match(css, /max-width:\s*767px/);
  assert.match(css, /mobile-nav/);
  assert.match(html, /id="needsYouNow"/);
  assert.match(html, /id="docAtWork"/);
  assert.match(html, /id="recentActivity"/);
  assert.match(js, /renderAggregates/);
  surfaces.forEach((surface) => {
    assert.match(surface, /href="\/deals"[^>]*>Deal Room</);
    assert.doesNotMatch(surface, /href="\/">Deal Room/);
  });
});
