"""Standalone dark HTML report, generated from measured results only."""
import html
import json


def render(data):
    esc = lambda v: html.escape(str(v))
    def table(title, headers, rows, note=''):
        return '<section><h2>' + esc(title) + '</h2><p>' + esc(note) + '</p><div class="scroll"><table><thead><tr>' + ''.join('<th>'+esc(h)+'</th>' for h in headers) + '</tr></thead><tbody>' + ''.join('<tr>'+''.join('<td>'+esc(v)+'</td>' for v in row)+'</tr>' for row in rows) + '</tbody></table></div></section>'
    content = table('Dataset', ['Kind','Assumed current rows','Measured rows'], [(k,data['scale']['assumed_current'][k],v) for k,v in data['scale']['nodes'].items()],data['scale']['assumption'])
    entries = data['inventory']
    content += table('Migration inventory', ['Table','Discriminator / reference','Kinds','Evidence'], [(e['table'], '; '.join(p['kind_column']+' / '+p['id_column']+' ('+p['id_type']+')' for p in e['pairs']),'; '.join(', '.join(p['kinds']) or 'Open vocabulary; see definition and MCP usages in JSON' for p in e['pairs']), e['file']+':'+str(e['line'])) for e in entries], 'Search covers all migration CREATE TABLE bodies plus the ALTER-added Tour pointer and evidence_source discriminator. This broad inventory includes provenance locators and taxonomy labels; those are not all graph edges. JSON carries full scalar columns, definitions, hashes, and MCP usage locations. candidate_pool is the renamed prospect_pool.')
    tests = {d:{t['test']:t for t in data['integrity'][d]} for d in 'ABC'}
    names = list(dict.fromkeys(t['test'] for d in 'ABC' for t in data['integrity'][d]))
    content += table('Integrity', ['Bad write','A typed','B registry','C baseline'], [(n,*[('REJECT '+str(tests[d][n]['sqlstate']) if tests[d][n]['rejected'] else 'ACCEPT') if n in tests[d] else 'No registry surface' for d in 'ABC']) for n in names], 'Raw SQL storage probes, rolled back independently. Undefined typed target columns reject structurally (42703), not by FK. Baseline preserves fixed-source FK and selected kind/uniqueness checks; no target-existence FK. Baseline is an identity projection, not a replay of envelope/permission logic.')
    latency = data['context']['designs']
    content += table('Depth-two context latency', ['Design','p50 ms','p95 ms','p50 range across runs','Errors'], [(d,round(latency[d]['p50_ms'],3),round(latency[d]['p95_ms'],3),[round(x,3) for x in latency[d]['p50_range_ms']],latency[d]['errors']) for d in 'ABC'], data['context']['definition'] + f" {data['context']['samples_per_run']} identical uniformly sampled refs per run; {data['context']['repeats']} interleaved repetitions. Results compared by hash for every query. Median result vertices {data['context']['cardinality']['median']}; maximum {data['context']['cardinality']['max']}.")
    write_rows, lock_rows = [], []
    import statistics
    for d in 'ABC':
        for op in ('insert','update','delete'):
            runs = [r[op] for r in data['writes'][d]['runs']]
            rates = [r['transactions_per_second'] for r in runs]
            write_rows.append((d,op,round(statistics.median(rates),1),[round(min(rates),1),round(max(rates),1)],round(statistics.median(r['p95_ms'] for r in runs),3)))
        for label in sorted({r['workload'] for r in data['writes'][d]['concurrent']}):
            runs = [r for r in data['writes'][d]['concurrent'] if r['workload'] == label]
            lock_rows.append((d,label,round(statistics.median(r['operations_per_second'] for r in runs),1),round(statistics.median(r['p95_ms'] for r in runs),3),sum(r['samples_with_waiters'] for r in runs),max(r['max_waiters'] for r in runs),sum(r['errors'] for r in runs)))
    content += table('Domain row plus three links write cost', ['Design','Operation','Median transactions/s','Range','p95 ms'],write_rows,'Each operation commits with fsync and synchronous_commit enabled. Update changes payload and all three target IDs; delete removes links then domain and registry. SQL round trips and constraint checks are timed; no batching advantage for a side. All successful writes commit and are later verified absent after deletion.')
    diagnostic = data.get('fk_index_diagnostic')
    if diagnostic:
        def operators(plan):
            return [plan['Node Type']] + [op for child in plan.get('Plans',[]) for op in operators(child)]
        content += table('FK index diagnostic', ['Configuration','Lookup execution ms','Operators','Rows returned','Shared blocks hit'],[(label,diagnostic[key][0]['Execution Time'],', '.join(operators(diagnostic[key][0]['Plan'])),diagnostic[key][0]['Plan']['Actual Rows'],diagnostic[key][0]['Plan'].get('Shared Hit Blocks',0)) for label,key in [('Without nullable-FK index','before'),('With nullable-FK index','after')]],diagnostic['purpose'])
    content += table('Eight concurrent writers', ['Design','Workload','Median cycles/s','p95 ms','10ms samples with waits','Max waiting writers','Errors'],lock_rows,'Independent cycle = insert + update + delete transactions. Hotspot = same domain row and its links, with a deliberate 1ms hold to force contention. pg_stat_activity samples measure observed lock occupancy, not exact wait time. Thread setup is included in throughput. Full raw repetition data is in JSON.')
    content += table('Registry drift and killed transactions', ['Design','Midpoint','Readback'],[(r['design'],r['midpoint'],json.dumps({k:v for k,v in r.items() if k not in ('design','midpoint')})) for r in data['drift']], 'pg_terminate_backend kills only a backend in the owned temporary cluster. Same-transaction uncommitted rows disappear. A committed registry-only row survives without a domain row. Integrity tests also show domain deletion can leave B edges pointing at a registry tombstone.')
    content += table('Online migration rehearsal', ['Target','SQL statements','Backfill passes','Backfill s','CDC changes','Writer cycles / errors','Cutover attempt + lock ms','Writer max cycle ms','Match after dual-write'],[(r['design'],r['statements'],r['backfill_passes'],round(r['backfill_s'],3),r['cdc_rows_replayed'],str(r['writer_cycles'])+' / '+str(len(r['writer_errors'])),round(r['cutover_attempt_and_lock_ms'],2),round(r['writer_max_cycle_ms'],2),r['post_cutover_dual_write_matched']) for r in data['migration']], 'SQL files alongside this report contain executable shadow setup, transactional capture, repeatable-read backfill, ordered replay, read-view cutover, and synchronous dual-write. Statements count client-submitted SQL including transaction control; scans count every UNION arm. Cutover uses bounded NOWAIT retries that release partial locks. Equality checks run after the writer stops. This proves continued writes with bounded queuing, not zero write latency. Existing invalid data, identifier mappings, grants, and app writer cutover remain deployment work; this does not authorize production migration.')
    plans = ''.join('<details><summary>Design '+d+' · EXPLAIN (ANALYZE, BUFFERS)</summary><pre>'+esc(json.dumps(latency[d]['plan'],indent=2))+'</pre></details>' for d in 'ABC')
    inventory_full = ''.join('<details><summary>'+esc(e['table'])+' · scalar columns and source definition</summary><pre>'+esc(json.dumps(e,indent=2))+'</pre></details>' for e in entries)
    methods = esc(data['methodology'])
    if 'index_tuning' in data:
        t = data['index_tuning']
        methods += '<br><br>' + esc(f"Tuning correction: the initial A design had a generated kind/ID read index but no indexes on its nullable FK columns. Adding {t['nullable_fk_indexes_added']} partial FK indexes changed median A delete throughput from {t['old_A_delete_transactions_per_second']:.1f} to {t['new_A_delete_transactions_per_second']:.1f} transactions/s. All three sides were rerun after tuning. The untuned-results.json file is retained for diagnosis and is superseded.")
    return '''<!doctype html><html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Link model bake-off</title><style>
    :root{color-scheme:dark}*{box-sizing:border-box}body{margin:0;color:#e8eef8;background:radial-gradient(ellipse at top right,#11233c,transparent 60%),#060a10;font:15px/1.55 system-ui,sans-serif}main{max-width:1300px;margin:auto;padding:40px 24px}h1,h2{font-family:Impact,'Arial Narrow',sans-serif;letter-spacing:.04em;font-weight:500}h1{font-size:44px;margin:10px 0}h2{color:#f9ac6b}section,.verdict{padding:24px;margin:24px 0;background:#0e1824bb;border:1px solid #28405c;border-radius:14px;backdrop-filter:blur(16px)}.verdict{border-left:5px solid #ef853b;animation:enter .5s ease}th,td{text-align:left;padding:11px;border-bottom:1px solid #26374b;vertical-align:top}th{color:#9cb7d4;font-size:12px;text-transform:uppercase}table{width:100%;border-collapse:collapse}tbody tr:hover{background:#18304a}.scroll{overflow:auto}p{color:#b7c6d8}a{color:#ffb171}input{background:#12243b;color:white;border:1px solid #375471;padding:12px;border-radius:8px;width:100%}details{margin:10px 0;border:1px solid #294059;border-radius:8px;padding:12px}summary{cursor:pointer}pre{white-space:pre-wrap;word-break:break-word;font:12px/1.5 monospace;color:#bcd0e8}nav{display:flex;gap:18px;flex-wrap:wrap}.tag{color:#ffa45f;font:12px monospace}@keyframes enter{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:translateY(0)}}@media(prefers-reduced-motion:reduce){*{animation:none!important}}
    </style><main><span class="tag">POSTGRESQL 18 · LOCAL SOCKET ONLY · SYNTHETIC DATA</span><h1>Link model bake-off</h1><div class="verdict"><h2>Choose typed links when domain existence must hold for every SQL writer.</h2><p>''' + esc(data['verdict']) + '''</p><p><strong>The verdict flips to a registry</strong> when reverse domain existence and deletion cleanup are enforced in the database, every legacy key has a collision-safe mapping, and measured context-read savings or frequent kind additions outweigh registry lifecycle and migration costs. The registry specified here fails the reverse-existence tests. Same-transaction insertion fixes crash drift but does not fix committed bypasses.</p></div><nav><a href="results.json">Raw results</a><a href="c-to-a.sql">C → A SQL</a><a href="c-to-b.sql">C → B SQL</a></nav><p>Filter measurement rows or expand source evidence below.</p><input id="filter" aria-label="Filter rows" placeholder="Filter tables, probes, or designs">''' + content + '<section><h2>Plans and inventory evidence</h2>' + plans + inventory_full + '</section><section><h2>Method and limits</h2><p>'+methods+'</p><p>Primary references: <a href="https://www.postgresql.org/docs/18/ddl-constraints.html">PostgreSQL 18 constraints</a>, <a href="https://www.postgresql.org/docs/18/sql-altertable.html">ALTER TABLE locking</a>, <a href="https://www.postgresql.org/docs/18/sql-createindex.html">Concurrent index builds</a>.</p><pre>'+esc(json.dumps(data['environment'],indent=2))+'</pre></section></main><script>document.getElementById("filter").addEventListener("input",e=>{const q=e.target.value.toLowerCase();document.querySelectorAll("tbody tr").forEach(r=>r.hidden=!r.textContent.toLowerCase().includes(q));});</script></html>'
