"""ORDER 39 step 4 — render targets for the two converted markdown ledgers.

WHY THIS IS ITS OWN MODULE AND NOT AN EDIT TO targets.py. At the time this was
written, `exporters/targets.py` was uncommitted-modified by the concurrent ORDER
37 session (`git status` showed ` M exporters/targets.py`). Editing the same file
from a second session is exactly the two-writer hazard this whole stream exists to
retire, and ORDER 24's log already records the standing concurrency instruction —
do not touch another live order's file. The builders therefore live here, and
registration in targets.py is two lines the supervisor applies once ORDER 37
commits. Nothing about the render changes; only where the function text sits.

REGISTRATION (supervisor applies to exporters/targets.py; not applied here):

    from .ledger_targets import HUNT_REL, RECIP_REL, build_hunt_ledger, build_reciprocity

  and inside the TARGETS dict:

    "md-ledger-hunt": (HUNT_REL, build_hunt_ledger),
    "md-ledger-reciprocity": (RECIP_REL, build_reciprocity),

  Both share the `md-ledger` prefix so `--only md-ledger` refreshes the pair, the
  same prefix-match convenience `--only loop` and `--only compiled-rules` use.

THE RENDER PATHS ARE NOT THE SOURCE FILES, AND THAT IS DELIBERATE. ORDER 39 step 4
says the render should match "the original file's location/shape for any consumer
still reading it". It cannot yet, and writing to the original paths today would be
the ORDER 34 near-miss repeated on purpose: `DNA/Network/hunt-ledger.md` and
`DNA/Network/deals.md` are still HAND-WRITTEN by eleven live writer sites, and
deals.md additionally holds 27 deal records and four other sections that no part
of this order converts. An exporter pointed at either path would clobber a live
hand-maintained file on the next nightly run. These targets therefore render
alongside, with `.generated.md` names, until the supervisor's writer-repoint pass
lands and step 5 can retire the originals to pointer headers. Swapping the two
REL constants to the original paths is then a one-line change per file — and it
must not happen before the repoint, which is the whole ordering ruling.

PARTIAL BY CONSTRUCTION, AND IT SAYS SO. Two of nine entries across the two
ledgers are imported; seven are parked or review-listed on stop rules. Every
render prints its own coverage line in the header, because a short file that does
not explain its shortness is how a partial migration gets mistaken for a finished
one.
"""

from datetime import datetime, timezone

HUNT_REL = "DNA/Network/hunt-ledger.generated.md"
RECIP_REL = "DNA/Network/deals-reciprocity.generated.md"

# Entry totals in each SOURCE ledger as frozen 2026-08-01, so the coverage line
# can state "N of M" honestly instead of only counting what happened to import.
# Frozen at CARR AI/Archive/snapshots/2026-08-01-*-freeze.zip.
SOURCE_ENTRY_TOTALS = {"hunt-ledger": 4, "deals-reciprocity": 5}

PARKED_NOTE = {
    "hunt-ledger": (
        "Not yet imported: **H2** (Hunt #1 — authored by the Monday brief, i.e. the "
        "`automation` actor, which no verb can issue, so its author cannot be preserved), "
        "**H3** (\"Honest note on hunt #1\" — no date stamp, no author stamp, no subject ref) "
        "and **H4** (\"Hunt #2 upgrade\" — author unstamped, no subject ref). All three are on "
        "Joe's consolidated review list. Their text is intact in the source file and in the "
        "freeze zip; nothing is lost."
    ),
    "deals-reciprocity": (
        "Not yet imported: **R2/R3** (Nilesh Patel, Jon Shaw — no date, no author, and they are "
        "hand-maintained counts that deals.md's own two-way-ledger section says to derive on "
        "demand rather than store) and **R4/R5** (Nate @ EOS, Trey @ Lazzarri — each exists in "
        "the vendor book twice, un-merged, so the lone-name rule bars picking a ref). All four "
        "are on Joe's consolidated list. Note also that R1's referral RELATIONSHIP is not "
        "repeated here: it is already carried by the intro graph as party_link edges "
        "V-SUP-051 → C-155 and V-SUP-051 → L-208. This render carries the commercial "
        "arrangement, which no edge holds."
    ),
}


def _header(title, ledger, imported, subtitle):
    total = SOURCE_ENTRY_TOTALS[ledger]
    return [
        f"# {title}",
        "",
        "> **GENERATED from the CARR record layer — do not hand-edit.**",
        f"> {subtitle}",
        ">",
        f"> **Coverage: {imported} of {total} entries from the source ledger.** "
        f"{PARKED_NOTE[ledger]}",
        ">",
        "> To add an entry, do not edit this file — record it in the record layer and this "
        "render refreshes. Pre-conversion original frozen at "
        "`CARR AI/Archive/snapshots/2026-08-01-*-freeze.zip`.",
        "",
    ]


def _fetch(cur, ledger):
    cur.execute(
        "select entry_id, entry_date, author, subject_ref, subject_name, subject_type, "
        "       summary, detail "
        "  from v_md_ledger_entry where ledger = %s "
        " order by entry_date desc, entry_id, subject_ref", (ledger,))
    return cur.fetchall()


def _group(rows):
    """One block per ENTRY, listing every subject it touched.

    The import writes one activity row per (entry, subject) so each subject's own
    timeline carries the entry — that is what "events on the subjects they touched"
    means. But the LEDGER reads as one line per hunt, not five, so the render
    regroups. summary/detail are identical across an entry's rows by construction.
    """
    out = []
    for r in rows:
        entry_id, date, author, ref, name, stype, summary, detail = r
        if out and out[-1]["entry_id"] == entry_id:
            out[-1]["subjects"].append((ref, name, stype))
        else:
            out.append({"entry_id": entry_id, "date": date, "author": author,
                        "summary": summary, "detail": detail,
                        "subjects": [(ref, name, stype)]})
    return out


def _render(tmp_path, cur, ledger, title, subtitle):
    entries = _group(_fetch(cur, ledger))
    lines = _header(title, ledger, len(entries), subtitle)

    if not entries:
        lines += ["*No entries imported yet.*", ""]
    for e in entries:
        lines += [f"## {e['date']} — {e['summary']}", "",
                  f"*Entry `{e['entry_id']}` · recorded by {e['author']} · "
                  f"{len(e['subjects'])} subject(s) touched*", ""]
        for ref, name, stype in e["subjects"]:
            lines.append(f"- `{ref}` — {name} ({stype})")
        lines += ["", e["detail"], ""]

    lines += [f"*Exported: {datetime.now(timezone.utc).isoformat()} · "
              f"{len(entries)} entr(y/ies)*", ""]
    tmp_path.write_text("\n".join(lines))
    # (count, rows) — the shape every builder in targets.py returns.
    return len(entries), [[e["entry_id"], str(e["date"]), e["author"],
                           ", ".join(s[0] for s in e["subjects"])] for e in entries]


def build_hunt_ledger(tmp_path, cur):
    return _render(
        tmp_path, cur, "hunt-ledger", "Vendor Discovery — Hunt Ledger",
        "The run-log for the weekly vendor-discovery hunt (engine.md Section 5). Read before "
        "each hunt so nobody is re-proposed.")


def build_reciprocity(tmp_path, cur):
    return _render(
        tmp_path, cur, "deals-reciprocity", "Reciprocity Ledger — vendors you plug in most",
        "Who sends us business and what we owe back. The referral RELATIONSHIPS themselves are "
        "the intro graph (`who-do-we-know`); this ledger carries the standing arrangements that "
        "sit on top of them.")
