-- 0474_reinstate_canonical_edit_control.sql
--
-- Reinstate the enforcement control `canonical_edit`, retired by
-- 0348_pr_only_main_ruleset_control.sql on 2026-08-27 (WR-000019 slice S3) when
-- hooks/canonical-edit-gate.py was deleted.
--
-- AUTHORITY: Joe's ruling of 2026-09-01, decision
-- 7f48abf6-6255-4e2c-8e7b-27eb9145adbe -- "Reinstate (Recommended)." Repo
-- Hygiene Program, WR-000040, plan PLAN-22ff72ae82c5-v2, slice R02, landing
-- phase (packet R02-L.v1). The gate returns in this same commit with its three
-- allowance dispositions applied; this migration makes the control catalog say
-- so.
--
-- NUMBER CLAIMED BY A FRESH SCAN, not by assumption: 59 remote refs were walked
-- for migrations/*.sql, yielding 343 distinct files, highest claimed 0473
-- (0473_restore_ops_backup_default_privilege_after_0451.sql, open in PR #841).
-- 0474 was free at scan time.
--
-- FORWARD-ONLY. This does not revert 0348. It supersedes the single fact in
-- 0348 that is no longer true -- that no installed control binds the canonical
-- tree at edit time -- and leaves everything else 0348 did standing.
--
-- ── THE RULE-BINDING HALF: DECIDED, AND THE DECISION IS "RESTORE ONLY WHAT
--    0348 REMOVED" ─────────────────────────────────────────────────────────────
-- The proposed draft left three options open (dual-bind rule 4a53ff82 to both
-- controls / move it back / leave the binding table alone) and refused to guess.
-- The live database answers it, and the answer is the third:
--
--   * ops.rule_control_binding holds SIX rows in total, for six controls
--     (ci_gates, completion_evidence, conduct_stop, control-plane-workflow-
--     manifest, delegation_names_model_and_effort, human_authority_runtime).
--     It is not the general rule-to-control mechanism; most catalog controls
--     have no row in it at all.
--   * Rule 4a53ff82-cb3f-4a0c-94a5-1a6e0b8b96c8 has NO binding row, and had
--     none before 0348 either -- 0348's own guard refused to delete
--     canonical_edit if it carried any binding, and it proceeded, which proves
--     the count was zero.
--   * So a binding row for canonical_edit would not be a restoration. It would
--     be new state this rule has never had, and it would require inventing a
--     statement_hash and a binding_contract with no authoritative source.
--
-- Restoring exactly what was removed -- the catalog row, nothing else -- is the
-- symmetric, provable change. The rule-to-control association for 4a53ff82
-- lives in ops/config/rule-enforcement-map.json, which is where 0348 actually
-- performed its reassignment, and that file is where this commit records the
-- dual-coverage description: pr_only_main_ruleset still carries the rule at
-- merge, canonical_edit carries it again at the edit.
--
-- WHAT THIS DELIBERATELY DOES NOT DO:
--   * It does not touch pr_only_main_ruleset. That control is real, installed
--     and server-side, and keeps carrying what it carries. This ADDS an earlier
--     binding moment; it does not retire the later one.
--   * It does not touch git_writer or staging_attribution. R02 reinstates ONE
--     of the three gates #722 retired; the other two stay retired.
--   * It does not rebind rule 308ef1de, which belonged to git-writer-gate.py.

-- NO explicit begin/commit: the runner wraps every migration from 0339_
-- onward in a single transaction and refuses transaction control of its own.
-- (The R02 proposed draft carried begin/commit; caught by local-db-ci.)

-- ── the control comes back ──────────────────────────────────────────────────
-- Column set matches what 0348 seeded pr_only_main_ruleset with. verified_at is
-- set because the catalog's own CHECK (installed_catalog_control_is_verified)
-- refuses an installed control with a null verified_at.
-- Rendered by ops/sync_control_catalog.py --render-control canonical_edit, not
-- hand-written. ops/control-catalog-parity-gate.py compares the catalog row
-- byte-for-byte against '; '.join(map implementation) and '; '.join(map test);
-- a hand-written implementation_ref drifted from the map and failed that gate
-- on the first local-db-ci run. Regenerate rather than edit.
-- GENERATED by ops/sync_control_catalog.py; never hand-edit.
insert into ops.enforcement_control_catalog
    (control_key, implementation_ref, test_ref, enforcement_class, installed, verified_at, updated_at)
values ('canonical_edit', 'hooks/canonical-edit-gate.py', 'ops/canonical-edit-gate-selftest.py', 'deny_gate', true, now(), now())
on conflict (control_key) do update set
    implementation_ref = excluded.implementation_ref,
    test_ref           = excluded.test_ref,
    enforcement_class  = excluded.enforcement_class,
    installed          = excluded.installed,
    verified_at        = excluded.verified_at,
    updated_at         = now();

-- ── post-conditions ─────────────────────────────────────────────────────────
do $$
declare
  bindings integer;
begin
  if not exists (select 1 from ops.enforcement_control_catalog
                  where control_key = 'canonical_edit') then
    raise exception '0474 FAILED: canonical_edit is not in the catalog after the insert';
  end if;

  if not exists (select 1 from ops.enforcement_control_catalog
                  where control_key = 'pr_only_main_ruleset') then
    raise exception '0474 FAILED: pr_only_main_ruleset was disturbed; this '
                    'migration must ADD an earlier binding moment, never '
                    'remove the later one';
  end if;

  if exists (select 1 from ops.enforcement_control_catalog
              where control_key in ('git_writer', 'staging_attribution')) then
    raise exception '0474 FAILED: git_writer or staging_attribution came back; '
                    'R02 reinstates canonical_edit only, and those two stay '
                    'retired';
  end if;

  -- Restoring the pre-0348 shape means zero bindings, exactly as 0348 found it.
  select count(*) into bindings
    from ops.rule_control_binding
   where control_key = 'canonical_edit';
  if bindings <> 0 then
    raise exception '0474 FAILED: canonical_edit unexpectedly carries % rule '
                    'binding(s); this migration restores the catalog row only', bindings;
  end if;
end $$;

