-- Findings manifest coverage for rule 729770dd-5a88-4521-84ef-10210c886ba4.
-- CI enforces declared manifest coverage; semantic defect and fix judgments remain advisory.
-- GENERATED by ops/sync_control_catalog.py; never hand-edit.
insert into ops.enforcement_control_catalog
    (control_key, implementation_ref, test_ref, enforcement_class, installed, verified_at, updated_at)
values ('findings_coverage', 'ops/findings-coverage-gate.py; ops/ci.sh', 'ops/findings-coverage-gate-selftest.py', 'deny_gate', true, now(), now())
on conflict (control_key) do update set
    implementation_ref = excluded.implementation_ref,
    test_ref           = excluded.test_ref,
    enforcement_class  = excluded.enforcement_class,
    installed          = excluded.installed,
    verified_at        = excluded.verified_at,
    updated_at         = now();
