-- rollback: forward-only — deleting the row would un-register a control a rule approval may then cite; retire it with a guarded retirement migration like 0836
-- 0862_register_github_burst_guard_control.sql
--
-- REGISTER THE ENFORCEMENT CONTROL `github-burst-guard`.
--
-- WHY THIS EXISTS. approve-rule refuses to activate rule 74ddb23c ("never burst
-- GitHub") with "rule-control binding refused: registered installed controls are
-- missing {github-burst-guard}". The hook that enforces it,
-- hooks/github-burst-guard.py (PR 1630), is a PreToolUse deny gate on Bash with
-- its own selftest, ops/github-burst-guard-selftest.py, which ops/ci.sh runs on
-- every push. The repository now declares the control in
-- ops/config/rule-enforcement-map.json and
-- ops/config/control-enforcement-classes.v1.json; this migration is the
-- production projection of that declaration, rendered by
--   ops/sync_control_catalog.py --render-control github-burst-guard
-- and never hand-written, because ops/control-catalog-parity-gate.py compares
-- the catalog row byte-for-byte against the map.
--
-- WHAT THIS DOES NOT DO. It adds no rule_control_binding row and activates no
-- rule: 74ddb23c stays proposed until a human approves it. It only makes the
-- control exist so that approval can name it.

-- GENERATED by ops/sync_control_catalog.py; never hand-edit.
insert into ops.enforcement_control_catalog
    (control_key, implementation_ref, test_ref, enforcement_class, installed, verified_at, updated_at)
values ('github-burst-guard', 'hooks/github-burst-guard.py', 'ops/github-burst-guard-selftest.py', 'deny_gate', true, now(), now())
on conflict (control_key) do update set
    implementation_ref = excluded.implementation_ref,
    test_ref           = excluded.test_ref,
    enforcement_class  = excluded.enforcement_class,
    installed          = excluded.installed,
    verified_at        = excluded.verified_at,
    updated_at         = now();

-- post-conditions
do $$
begin
  if not exists (select 1 from ops.enforcement_control_catalog
                  where control_key = 'github-burst-guard'
                    and installed
                    and verified_at is not null
                    and enforcement_class = 'deny_gate'
                    and implementation_ref = 'hooks/github-burst-guard.py'
                    and test_ref = 'ops/github-burst-guard-selftest.py') then
    raise exception '0862 FAILED: github-burst-guard is not an installed, verified deny_gate after the insert';
  end if;
end $$;
