// GENERATED SNAPSHOT — do not hand-edit. The pinned doctrine taxonomy the
// hierarchical Jev reranker walks: content class -> document -> section.
// Captured from the live doctrine-index at doctrine generation 1247 on
// 2026-09-29, shared visibility only, with the two dossier_narrative client
// documents left out because this repository is public. A new snapshot is a
// new file with a new id and digest; jev-rerank.js refuses any taxonomy whose
// digest is not the pinned one, and mcp-server/test/jev-rerank.test.mjs
// recomputes this digest from the content below.

export const DOCTRINE_TAXONOMY_SNAPSHOT_ID = "doctrine-taxonomy.2026-09-29.v1";
export const DOCTRINE_TAXONOMY_DIGEST = "sha256:8db7c738710bed686aacb3600d2d61def19b30d8fafa37494ba9165e56bafa80";

export const DOCTRINE_TAXONOMY_SNAPSHOT = Object.freeze({
  snapshot_id: DOCTRINE_TAXONOMY_SNAPSHOT_ID,
  digest: DOCTRINE_TAXONOMY_DIGEST,
  doctrine_generation: 1247,
  captured_at: "2026-09-29",
  classes: Object.freeze({
    distillation: "Distilled takeaways from outside sources and ideas: studies, posts and research filed for later adoption.",
    index: "Folder indexes that only point to where other material lives.",
    playbook: "Business playbooks: marketing, outreach, lead generation, social media and client relationship craft.",
    reference: "Reference records: plans, reviews, baselines, handoffs and design decisions describing what exists or was decided.",
    sop: "Standard operating procedures and runbooks: how to operate, change, recover or repair a system step by step.",
  }),
  documents: Object.freeze([
    Object.freeze({ slug: "2026-07-23-geofencing-become-the-source", class: "distillation", title: "Idea: Geofence where doctors gather + become the SOURCE of deals (flip the vendor flywheel)" }),
    Object.freeze({ slug: "2026-07-23-tiktok-viral-topic-mining", class: "distillation", title: "TikTok viral topic mining for content" }),
    Object.freeze({ slug: "2026-07-30-agent-systems-explainer-takeaways", class: "distillation", title: "The 3.7M-view agent-systems explainer — two build-spec adoptions, heavy validation, one content lesson" }),
    Object.freeze({ slug: "2026-07-30-anthropic-expertise-study", class: "distillation", title: "Anthropic's expertise study — VERIFIED, and it's both personal validation and citable content ammo" }),
    Object.freeze({ slug: "2026-07-30-app-send-rail", class: "distillation", title: "THE SEND RAIL — review-and-tap-to-send inside the app (Joe's design, gate-compliant, Wave 5)" }),
    Object.freeze({ slug: "2026-07-30-arcads-motion-skill-note", class: "distillation", title: "The Arcads motion-animation skill (413K views) — rejected by PRECEDENT, one magnet observation kept" }),
    Object.freeze({ slug: "2026-07-30-calculations-through-code-rule", class: "distillation", title: "Standing rule: run calculations through code (scoped) — Joe's ruling 2026-07-30" }),
    Object.freeze({ slug: "2026-07-30-capability-scout-pipeline", class: "distillation", title: "The self-expanding skills pipeline (119K views) — adopt as THE TOOL SCOUT lane + four design details for our own pipelines" }),
    Object.freeze({ slug: "2026-07-30-claude-code-101-format-lesson", class: "distillation", title: "The 4.6M-view \"101 for a named profession\" format — a craft specimen, not a system change" }),
    Object.freeze({ slug: "2026-07-30-coldiq-magnet-specimen", class: "distillation", title: "The ColdIQ comment-gated magnet post — a live specimen of the adopted formula, plus the data-backed-magnet play" }),
    Object.freeze({ slug: "2026-07-30-cole-six-openers", class: "distillation", title: "Nicolas Cole's six openers + the first-chip principle — straight into craft-patterns" }),
    Object.freeze({ slug: "2026-07-30-cole-thinking-partner-prompts", class: "distillation", title: "Cole's three thinking-partner prompts — two adoptions, one validation, one quotable law" }),
    Object.freeze({ slug: "2026-07-30-confidence-tags-convention", class: "distillation", title: "The advisor-prompt post — one convention adopted: confidence tags on intel outputs" }),
    Object.freeze({ slug: "2026-07-30-context-audit-unhobbling", class: "distillation", title: "The context-audit guide (\"Anthropic deleted 80% of its own instructions\") — the deletion discipline our review cycle was missing" }),
    Object.freeze({ slug: "2026-07-30-dickie-bush-harsh-truths-takeaways", class: "distillation", title: "Takeaways from Dickie Bush's \"9 harsh truths\" post — adoptions + honest rejections" }),
    Object.freeze({ slug: "2026-07-30-distribution-roadmap-takeaways", class: "distillation", title: "Takeaways from the \"full distribution roadmap\" post — two real adoptions, one missing channel exposed, validations noted" }),
    Object.freeze({ slug: "2026-07-30-drive-endgame-human-tree", class: "distillation", title: "Drive endgame requirement (Joe, stated 7/30): human-optimized folder tree, OneDrive-like, manually browsable" }),
    Object.freeze({ slug: "2026-07-30-eptwts-distribution-101-takeaways", class: "distillation", title: "Takeaways from EP's \"distribution 101\" mega-guide (X / YouTube / shortform) — graph mechanics adopted, one doctrine tension flagged, account-farming rejected" }),
    Object.freeze({ slug: "2026-07-30-gh-render-issues-pattern-note", class: "distillation", title: "gh-render-issues — pattern validation + optional build tooling (minor filing, deliberately brief)" }),
    Object.freeze({ slug: "2026-07-30-gherkin-evals-format", class: "distillation", title: "The /gherkin-stories post — adopt Given/When/Then as the house EVAL format, with the mandatory negative case" }),
    Object.freeze({ slug: "2026-07-30-gojiberry-linkedin-mcp-rejection", class: "distillation", title: "GojiBerry LinkedIn MCP (post + video walkthrough) — REJECTED, with the reasoning on record" }),
    Object.freeze({ slug: "2026-07-30-gott-linkedin-prompts-note", class: "distillation", title: "The LinkedIn-prompts listicle — two small keepers, rest already covered (brief)" }),
    Object.freeze({ slug: "2026-07-30-landingfolio-taste-injection", class: "distillation", title: "Taste injection — REVISED: vendor tool rejected, build THE TASTE VAULT instead (Joe's call)" }),
    Object.freeze({ slug: "2026-07-30-linkedin-lead-magnet-blueprint-takeaways", class: "distillation", title: "Takeaways from \"The Viral LinkedIn Post Blueprint\" (Notion guide) — adopt the magnet, moderate the mechanic" }),
    Object.freeze({ slug: "2026-07-30-local-dictation-tool-note", class: "distillation", title: "Open-source local dictation (Wispr Flow alternative) — small quality-of-life note for the capture stack" }),
    Object.freeze({ slug: "2026-07-30-one-person-ai-business-post", class: "distillation", title: "The \"one-person AI business\" blueprint (499K views) — mostly a mirror; two adoptions, one content angle" }),
    Object.freeze({ slug: "2026-07-30-onedrive-sweep-and-structure", class: "distillation", title: "CARR OneDrive connected + swept — templates captured, structure assessed (light-touch verdict)" }),
    Object.freeze({ slug: "2026-07-30-opportunity-post-takeaways", class: "distillation", title: "Takeaways from the Nurijanian /opportunity post — adopt into the system (Joe: \"Take all these things into the system for sure\")" }),
    Object.freeze({ slug: "2026-07-30-permit-postcard-transfer", class: "distillation", title: "The permit-postcard business post — three transfers into OUR model, funnel mechanics rejected" }),
    Object.freeze({ slug: "2026-07-30-pixelrag-watch-item", class: "distillation", title: "PixelRAG (visual RAG, open-source) — watch-item, principle already ours, one future capability named" }),
    Object.freeze({ slug: "2026-07-30-prompts-as-images-rejection", class: "distillation", title: "The \"prompts as images to cut API bills 70%\" trick (2.7M views) — REJECTED for our system, mechanics on record" }),
    Object.freeze({ slug: "2026-07-30-retrospective-rule-mining", class: "distillation", title: "Retrospective rule-mining from session history — bootstrap the teaching layer pre-loaded (small link, real idea)" }),
    Object.freeze({ slug: "2026-07-30-search-console-agent-loop", class: "distillation", title: "Search Console → agent loop (companion to 2026-07-30-distribution-roadmap-takeaways.md item 2)" }),
    Object.freeze({ slug: "2026-07-30-selfhosted-tools-list-note", class: "distillation", title: "The 50-self-hosted-tools listicle — one real adoption, one contingency, mostly pass (deliberately brief)" }),
    Object.freeze({ slug: "2026-07-30-study-sweep-manifest", class: "distillation", title: "⚑ STUDY-SWEEP MANIFEST — every 7/30 filing routed to its trigger (this file IS the work order)" }),
    Object.freeze({ slug: "2026-07-30-syndication-structures-thread", class: "distillation", title: "Nick Huber syndication-structures thread — domain knowledge merge + two advisory/content angles" }),
    Object.freeze({ slug: "2026-07-30-vacca-content-engine-takeaways", class: "distillation", title: "Takeaways from Alex Vacca's Claude Code LinkedIn content engine — six adoptions from a parallel build" }),
    Object.freeze({ slug: "2026-07-30-vectors-explainer-craft", class: "distillation", title: "\"Vectors are all you need\" (497K views) — explainer-craft moves + one quotable law; no system change" }),
    Object.freeze({ slug: "2026-08-01-doctorcre-domain-mascot", class: "distillation", title: "doctorcre.com domain + \"Doctor Cre\" mascot" }),
    Object.freeze({ slug: "2026-08-06-always-on-mac-mini-host", class: "distillation", title: "Always-on Mac mini as the system host" }),
    Object.freeze({ slug: "2026-08-07-tenex-metaharness-sdlc-takeaways", class: "distillation", title: "The Tenex MetaHarness essay — one real architectural gap, three partial gaps, four validations, one marketing lateral" }),
    Object.freeze({ slug: "idea-inbox-readme", class: "distillation", title: "Idea Inbox — the phone capture lane (created July 10, 2026)" }),
    Object.freeze({ slug: "00-context-index", class: "index", title: "00_Context — Folder Index" }),
    Object.freeze({ slug: "automation-index", class: "index", title: "Automation — Folder Index" }),
    Object.freeze({ slug: "clients-index", class: "index", title: "Clients — Folder Index (the shared client brain)" }),
    Object.freeze({ slug: "deal-management-index", class: "index", title: "Deal Management — Folder Index" }),
    Object.freeze({ slug: "leads-index", class: "index", title: "Leads — Folder Index" }),
    Object.freeze({ slug: "outreach-index", class: "index", title: "Outreach — Folder Index" }),
    Object.freeze({ slug: "prospects-index", class: "index", title: "Prospects/ — MOVED" }),
    Object.freeze({ slug: "reference-index", class: "index", title: "Reference — Folder Index" }),
    Object.freeze({ slug: "research-index", class: "index", title: "Research — Folder Index" }),
    Object.freeze({ slug: "root-index", class: "index", title: "CARR AI — Folder Index" }),
    Object.freeze({ slug: "ae-pipeline-sop", class: "playbook", title: "After Effects pipeline — the Claude -> AE \"hero cut\" pathway (SOP)" }),
    Object.freeze({ slug: "alabama-lead-system", class: "playbook", title: "The Alabama Lead System — and why it is not the Florida one" }),
    Object.freeze({ slug: "asset-checklist", class: "playbook", title: "Brand Asset Checklist" }),
    Object.freeze({ slug: "associate-lane-sop", class: "playbook", title: "The Associate Lane — the earliest signal that exists" }),
    Object.freeze({ slug: "brand-voice", class: "playbook", title: "CARR Brand Voice & Visual Identity" }),
    Object.freeze({ slug: "brokers", class: "playbook", title: "⛔ SUPERSEDED — listing brokers are now `brokers.xlsx` (July 7, 2026)" }),
    Object.freeze({ slug: "carr-colleague-contacts", class: "playbook", title: "CARR Colleague Contacts — who to call for what" }),
    Object.freeze({ slug: "carr-profile", class: "playbook", title: "CARR Profile — Shared Context" }),
    Object.freeze({ slug: "community-group-playbook-2026", class: "playbook", title: "Community Group Playbook 2026 — the regional practice-owner community" }),
    Object.freeze({ slug: "consequence-map", class: "playbook", title: "Consequence Map — see around corners before you decide" }),
    Object.freeze({ slug: "content-concept-library", class: "playbook", title: "Content Concept Library — evergreen post concepts by lane" }),
    Object.freeze({ slug: "content-fuel-engine", class: "playbook", title: "Content Fuel Engine — the automated substance harvest" }),
    Object.freeze({ slug: "content-inspiration-bank", class: "playbook", title: "Content Inspiration Bank" }),
    Object.freeze({ slug: "content-inspiration-bank-archive", class: "playbook", title: "Content Inspiration Bank — archive (spent and superseded substance)" }),
    Object.freeze({ slug: "copy-craft-masters", class: "playbook", title: "Copy-Craft Masters — what the greats do, distilled for Joe's voice" }),
    Object.freeze({ slug: "costar-playbook", class: "playbook", title: "CoStar Playbook — what's actually in there, and the ten workflows worth building" }),
    Object.freeze({ slug: "doctor-gathering-map", class: "playbook", title: "CARR Doctor-Gathering Map — South Alabama & Florida Panhandle" }),
    Object.freeze({ slug: "dso-detector-sop", class: "playbook", title: "The Corporate / DSO Associate Detector — address match" }),
    Object.freeze({ slug: "engine", class: "playbook", title: "Network Engine — how Claude runs the networking brain" }),
    Object.freeze({ slug: "enrichment-interview", class: "playbook", title: "Vendor Enrichment Interview — conversational gap-filling (never open the sheet)" }),
    Object.freeze({ slug: "evolution-guide", class: "playbook", title: "Lead System — Evolution Guide" }),
    Object.freeze({ slug: "facebook-ads-playbook-2026", class: "playbook", title: "Facebook Ads Playbook 2026 — CARR-branded paid playbook" }),
    Object.freeze({ slug: "facebook-strategy-2026", class: "playbook", title: "Facebook Strategy 2026 — CARR-branded local Page playbook" }),
    Object.freeze({ slug: "growth-stages-and-deferred-advice-2026", class: "playbook", title: "Growth Stages and Deferred Advice — the system's stage map" }),
    Object.freeze({ slug: "hooks-deep-reference-2026", class: "playbook", title: "Hooks — the deep reference" }),
    Object.freeze({ slug: "instagram-strategy-2026", class: "playbook", title: "Instagram Strategy 2026 — CARR-branded playbook" }),
    Object.freeze({ slug: "lead-magnet-five-numbers-2026-07-18", class: "playbook", title: "Five numbers that cost more than your rent" }),
    Object.freeze({ slug: "lead-sweep-explainer", class: "playbook", title: "The Lead Sweep — how it works, in plain English" }),
    Object.freeze({ slug: "lead-system", class: "playbook", title: "Lead & Prospecting System — Architecture and SOPs" }),
    Object.freeze({ slug: "lead-system-handoff", class: "playbook", title: "The Lead System — HANDOFF (built July 13, 2026)" }),
    Object.freeze({ slug: "lead-system-weekly", class: "playbook", title: "The Weekly Lead-System Run — SOP" }),
    Object.freeze({ slug: "lease-term-estimator", class: "playbook", title: "The Lease-Term Estimator — our best guess, and it says so on every row" }),
    Object.freeze({ slug: "linkedin-engagement-engine", class: "playbook", title: "LinkedIn Engagement Engine — the vendor-side counterpart to the X reply engine" }),
    Object.freeze({ slug: "linkedin-strategy-2026", class: "playbook", title: "LinkedIn Strategy 2026 — CARR-branded playbook" }),
    Object.freeze({ slug: "marketing-playbook", class: "playbook", title: "Marketing Playbook — transferable persuasion & content techniques" }),
    Object.freeze({ slug: "model-study-healthcarereguy-2026-07-18", class: "playbook", title: "Model account study: @HealthcareREguy (Michael Moreno)" }),
    Object.freeze({ slug: "national-accounts-screen-sop", class: "playbook", title: "National Accounts SCREEN — the AI-triage lane + the CoStar structured pull (implemented 2026-07-22)" }),
    Object.freeze({ slug: "national-accounts-toolkit", class: "playbook", title: "National Accounts Toolkit (ready-to-use assets)" }),
    Object.freeze({ slug: "objection-bank", class: "playbook", title: "Objection Bank + Outreach Levers — healthcare CRE" }),
    Object.freeze({ slug: "peer-gap-2026-07-18", class: "playbook", title: "Peer-gap pass — July 18, 2026 (first run)" }),
    Object.freeze({ slug: "performance-loop", class: "playbook", title: "Performance Loop — engagement evidence sets next month's mix" }),
    Object.freeze({ slug: "personal-brand-playbook-2026", class: "playbook", title: "Personal Brand — the distilled playbook and Joe's positioning" }),
    Object.freeze({ slug: "pipeline-craft", class: "playbook", title: "Pipeline Craft — Our Playbook (how top producers build the book)" }),
    Object.freeze({ slug: "pipeline-shared", class: "playbook", title: "Shared Pipeline — MERGED into the shared client brain" }),
    Object.freeze({ slug: "platform-playbook-2026", class: "playbook", title: "Platform Playbook 2026 — how Joe's posts should be built per platform" }),
    Object.freeze({ slug: "profile-audit-2026-07-20", class: "playbook", title: "Profile audit — FB / IG / LinkedIn vs the personal-brand checklist (July 20, 2026)" }),
    Object.freeze({ slug: "question-bank", class: "playbook", title: "Question Bank — the demand side of the content engine" }),
    Object.freeze({ slug: "radar-spec", class: "playbook", title: "The Radar — predictive demand intelligence (v1 spec)" }),
    Object.freeze({ slug: "referral-network", class: "playbook", title: "Upstream / Referral Network — give first, let it flow back" }),
    Object.freeze({ slug: "renewal-radar-sop", class: "playbook", title: "Renewal Radar — the SOP" }),
    Object.freeze({ slug: "social-media-workflow", class: "playbook", title: "Social Media Workflow & Folder Guide" }),
    Object.freeze({ slug: "style-contract", class: "playbook", title: "Joe's Style Contract — the pasteable parameter block" }),
    Object.freeze({ slug: "talking-head-scripts-2026-07", class: "playbook", title: "Talking-head scripts — batch 1 (July 2026)" }),
    Object.freeze({ slug: "target-dossier-sop", class: "playbook", title: "Target Dossier — the on-demand, read-only single-person workup (SOP)" }),
    Object.freeze({ slug: "templates", class: "playbook", title: "Approved Email & Outreach Rules" }),
    Object.freeze({ slug: "upstream-radar", class: "playbook", title: "The Upstream Radar — detecting leads BEFORE the entity files" }),
    Object.freeze({ slug: "ux-doctrine", class: "playbook", title: "UX Doctrine — how every surface stays friendly" }),
    Object.freeze({ slug: "vendor-by-industry-reference", class: "playbook", title: "Vendor Info by Industry — CARR corporate approach reference (all 12 categories)" }),
    Object.freeze({ slug: "vendor-intro-timeline", class: "playbook", title: "Vendor Intro Timeline — introducing the client to the right vendor, at the right stage" }),
    Object.freeze({ slug: "vendor-relationship-craft", class: "playbook", title: "Vendor Relationship Craft — Our Playbook (by vendor type)" }),
    Object.freeze({ slug: "video-scripts-five-numbers-2026-07-18", class: "playbook", title: "Talking-head series: \"Numbers that cost more than your rent\"" }),
    Object.freeze({ slug: "voice-samples", class: "playbook", title: "Voice samples and fingerprint" }),
    Object.freeze({ slug: "weekly-routine", class: "playbook", title: "Weekly Network Routine — capture, then brief" }),
    Object.freeze({ slug: "writing-rules", class: "playbook", title: "Writing Rules — Zero-Tolerance AI-Tell List" }),
    Object.freeze({ slug: "x-article-draft-medical-lease-2026-07-17", class: "playbook", title: "X Article draft: \"How a medical lease really works\" (Joe's rev 3, 2026-07-17)" }),
    Object.freeze({ slug: "x-article-playbook", class: "playbook", title: "X Article Playbook — long-form Articles for @joebookout" }),
    Object.freeze({ slug: "x-buildout-checklist", class: "playbook", title: "X Build-Out Checklist — finish the setup" }),
    Object.freeze({ slug: "x-following-cleanup", class: "playbook", title: "X Following Cleanup — working list" }),
    Object.freeze({ slug: "x-posting-spec", class: "playbook", title: "X Posting — how X folds into the social run" }),
    Object.freeze({ slug: "x-premium-plus-toolkit-2026-07-18", class: "playbook", title: "X Premium+ toolkit → strategy (what to actually use, and how)" }),
    Object.freeze({ slug: "x-reply-engine-2026", class: "playbook", title: "The Reply Engine" }),
    Object.freeze({ slug: "x-reply-run-sop", class: "playbook", title: "X Reply Run — the twice-daily engagement SOP" }),
    Object.freeze({ slug: "x-sound-design-playbook-2026", class: "playbook", title: "Sound Design Playbook — selecting sounds by NAME for motion clips (2026)" }),
    Object.freeze({ slug: "x-standalone-rewrites-2026-07-15", class: "playbook", title: "X Standalone Rewrites — before and after (July 15, 2026)" }),
    Object.freeze({ slug: "x-strategy-2026", class: "playbook", title: "X Strategy 2026 — the specialized playbook for @joebookout" }),
    Object.freeze({ slug: "x-topic-bank", class: "playbook", title: "X Topic Bank — the mixed bag" }),
    Object.freeze({ slug: "x-visual-content-playbook-2026", class: "playbook", title: "X Visual Content Playbook — the full toolkit, no boring repeat cards (2026)" }),
    Object.freeze({ slug: "x-writing-hooks-branding-playbook-2026", class: "playbook", title: "X Writing, Hooks, and Branding — the distilled playbook" }),
    Object.freeze({ slug: "2026-07-06-panhandle-healthcare-cre-snapshot", class: "reference", title: "Panhandle Healthcare CRE Snapshot — 5-County Pull" }),
    Object.freeze({ slug: "2026-07-25-pensacola-medical-dental-market", class: "reference", title: "Pensacola Metro Pull: Medical and Dental Office Vacancy, Rents, and Healthcare Development" }),
    Object.freeze({ slug: "audio-license-note", class: "reference", title: "Audio provenance — Brand Assets/Audio/" }),
    Object.freeze({ slug: "brand-assets-readme", class: "reference", title: "Brand Assets — READ THIS FIRST" }),
    Object.freeze({ slug: "broll-readme", class: "reference", title: "Stock B-roll library (Adobe Stock Free collection)" }),
    Object.freeze({ slug: "carr-clean-end-state-control-plane-roadmap", class: "reference", title: "CARR Clean-End-State Control-Plane Roadmap" }),
    Object.freeze({ slug: "carr-control-room-bduf", class: "reference", title: "CARR Control Room — Big Design Up Front" }),
    Object.freeze({ slug: "carr-mature-software-end-state-bduf", class: "reference", title: "CARR Mature Software End State — Big Design Up Front" }),
    Object.freeze({ slug: "carr-production-maturity-baseline", class: "reference", title: "CARR Production Maturity Baseline" }),
    Object.freeze({ slug: "carr-workspace-bduf", class: "reference", title: "CARR Workspace — Big Design Up Front" }),
    Object.freeze({ slug: "claude-native-context-design", class: "reference", title: "Claude native context and token efficiency design" }),
    Object.freeze({ slug: "codex-compaction-continuity-design", class: "reference", title: "Codex compaction continuity implementation design" }),
    Object.freeze({ slug: "costar-how-to", class: "reference", title: "CoStar — How-To for CARR Agents (property search, pre-tour, comps, renewal-hunting)" }),
    Object.freeze({ slug: "deal-intelligence-program-build-plan", class: "reference", title: "Deal Intelligence Program — Build Plan (Lev-derived capabilities)" }),
    Object.freeze({ slug: "dental-vertical-guide", class: "reference", title: "CARR Training — Dental Vertical Reference (build-out, sizing, creditworthiness, landlord pitch)" }),
    Object.freeze({ slug: "design-manager-operating-blueprint", class: "reference", title: "Design Manager Operating Blueprint and DoctorCRE Pilot Plan" }),
    Object.freeze({ slug: "doctorcre-private-product-heavy-build-plan", class: "reference", title: "DoctorCRE Private Product — Heavy Build and Shipping Plan" }),
    Object.freeze({ slug: "doctorcre-v5-astra-integration-review", class: "reference", title: "DoctorCRE v5 — independent review and repository-informed integration" }),
    Object.freeze({ slug: "doctorcre-v5-design-basis", class: "reference", title: "DoctorCRE v5 Design Basis and Requirement Disposition Register" }),
    Object.freeze({ slug: "doctorcre-v5-nurijanian-repo-review-2026-09-05", class: "reference", title: "DoctorCRE v5 — six-repository build and product review, September 5 2026" }),
    Object.freeze({ slug: "doctrine-search-zero-hit-fallback", class: "reference", title: "Doctrine search: the zero-hit fallback" }),
    Object.freeze({ slug: "enforcement-gate-telemetry", class: "reference", title: "Enforcement gate telemetry — how the hook stack is measured" }),
    Object.freeze({ slug: "frontier-finding-plan", class: "reference", title: "The Frontier Finding — plan of record for the parked production migration lane" }),
    Object.freeze({ slug: "integrity-activation-plan", class: "reference", title: "Integrity Activation Program — plan of record for unparking the production migration lane" }),
    Object.freeze({ slug: "library-readme", class: "reference", title: "Sound library (select, don't reuse)" }),
    Object.freeze({ slug: "maps-and-demographics", class: "reference", title: "CARR Mapping & Demographics — What's Available and How to Request" }),
    Object.freeze({ slug: "mechanism-doctrine-admission", class: "reference", title: "A new mechanism ships with its doctrine, or it does not ship" }),
    Object.freeze({ slug: "medical-vertical-guide", class: "reference", title: "CARR Training — Medical Vertical Reference (build-out, sizing, space-type fit)" }),
    Object.freeze({ slug: "named-agent-profiles", class: "reference", title: "Named agent profiles" }),
    Object.freeze({ slug: "nightly-exports-onedrive-wake", class: "reference", title: "Nightly exports: OneDrive pre-publish wake, caffeinate, and the daytime retry" }),
    Object.freeze({ slug: "open-questions", class: "reference", title: "Open Questions — unresolved knowledge the market hasn't answered us yet" }),
    Object.freeze({ slug: "other-healthcare-vertical-guide", class: "reference", title: "CARR Training — Other Healthcare Reference (Chiropractic + Therapy: build-out, parking, the low-TI angle)" }),
    Object.freeze({ slug: "pr-pipeline", class: "reference", title: "Scripted Review-and-Merge Pipeline" }),
    Object.freeze({ slug: "repo-accretion-control-program-build-plan", class: "reference", title: "Repo Accretion Control Program — Build Plan (Two-Way Ratchet operating model)" }),
    Object.freeze({ slug: "repo-hygiene-program-build-plan", class: "reference", title: "Repo Hygiene Program — Build Plan (Clean Tree operating model)" }),
    Object.freeze({ slug: "resource-collector-mechanism", class: "reference", title: "Resource Collector — local capacity/model-route launchd mechanism" }),
    Object.freeze({ slug: "room-bridge", class: "reference", title: "Partner Room Bridge" }),
    Object.freeze({ slug: "rule-delivery-load-layers", class: "reference", title: "Rule delivery: the three load layers, and the gate that keeps them honest" }),
    Object.freeze({ slug: "scheduler-cutover-coverage", class: "reference", title: "Scheduler cutover coverage: how much of the Mac has actually moved" }),
    Object.freeze({ slug: "session-trace-archive", class: "reference", title: "Session trace archive" }),
    Object.freeze({ slug: "snapshot-rebuild-fidelity", class: "reference", title: "The snapshot must describe the database its ledger claims" }),
    Object.freeze({ slug: "stock-license-note", class: "reference", title: "Stock photo provenance — Brand Assets/Photography/stock/" }),
    Object.freeze({ slug: "timebomb-audit", class: "reference", title: "Weekly time-bomb audit" }),
    Object.freeze({ slug: "vet-vertical-guide", class: "reference", title: "CARR Training — Veterinary Vertical Reference (build-out, sizing, the landlord pitch)" }),
    Object.freeze({ slug: "vision-vertical-guide", class: "reference", title: "CARR Training — Vision Vertical Reference (build-out, sizing, the retail duality, landlord pitch)" }),
    Object.freeze({ slug: "00-context-session-operating-style", class: "sop", title: "Session operating style (pointer)" }),
    Object.freeze({ slug: "api-pipeline-playbook", class: "sop", title: "API Pipeline Playbook — doctrine + parked candidates" }),
    Object.freeze({ slug: "benefit-summary-sop", class: "sop", title: "Benefit Summary Sheet — the post-close client deliverable" }),
    Object.freeze({ slug: "calendar-feed", class: "sop", title: "Calendar Feed - MOVED to the shared tier" }),
    Object.freeze({ slug: "calendar-feeds", class: "sop", title: "Calendar Feeds - both partners' schedules into the shared brain" }),
    Object.freeze({ slug: "claude-operating-rules", class: "sop", title: "Claude operating rules (Joe)" }),
    Object.freeze({ slug: "client-care-drip", class: "sop", title: "Client Care (post-close): the lane content and cadence" }),
    Object.freeze({ slug: "cloudflare-edge-sop", class: "sop", title: "Cloudflare Edge SOP — Worker releases, rollback, secrets, R2 backups, and domains" }),
    Object.freeze({ slug: "comp-record-template", class: "sop", title: "Comp Record — capture template (the Comps Engine, capture layer)" }),
    Object.freeze({ slug: "conversion-coverage", class: "sop", title: "Conversion coverage — SOP/workflow → code status" }),
    Object.freeze({ slug: "deal-analysis-toolkit", class: "sop", title: "Deal-Analysis Toolkit — Reference" }),
    Object.freeze({ slug: "deal-enrichment-sop", class: "sop", title: "Deal enrichment SOP — dropping a Copilot email summary into the Deal Room" }),
    Object.freeze({ slug: "deal-post-mortem-template", class: "sop", title: "Deal Post-Mortem: the internal capture at deal-won" }),
    Object.freeze({ slug: "deal-room-kit", class: "sop", title: "Deal Room Kit — activation-ready (idea-bank #14, pre-built)" }),
    Object.freeze({ slug: "dell-adoption-runbook", class: "sop", title: "Dell's setup walkthrough — guided, one step at a time" }),
    Object.freeze({ slug: "dell-onboarding-runbook-2026-08-01", class: "sop", title: "Dell onboarding runbook — the Monday sitting (in person at Dell's office)" }),
    Object.freeze({ slug: "diligence-and-valuation", class: "sop", title: "Diligence & Valuation — Our Playbook (what it's worth · what to verify · space-type & execution judgment)" }),
    Object.freeze({ slug: "dna-protocol", class: "sop", title: "DNA Protocol — how ANY session, either brain, touches shared files" }),
    Object.freeze({ slug: "document-factory-routing", class: "sop", title: "Document Factory — OneDrive routing doctrine" }),
    Object.freeze({ slug: "document-vault", class: "sop", title: "Document Vault — the capture convention (thin slice)" }),
    Object.freeze({ slug: "dr-cre-concept-2026-08-01", class: "sop", title: "Dr. CRE — concept brief v2" }),
    Object.freeze({ slug: "dr-cre-dialogue-mode-2026-08-01", class: "sop", title: "Dr. CRE — Dialogue Mode design spec v1" }),
    Object.freeze({ slug: "dr-cre-doctrine-2026-08-01", class: "sop", title: "The Dr. CRE Doctrine — the complete design for the most pleasing assistant ever built" }),
    Object.freeze({ slug: "dr-cre-voice-doctrine-2026-08-01", class: "sop", title: "The Voice of Doc — voice doctrine and audition kit" }),
    Object.freeze({ slug: "email-verification-sop", class: "sop", title: "Pre-send email verification, the standing workflow" }),
    Object.freeze({ slug: "engineering-workflow-sop", class: "sop", title: "Engineering Workflow SOP — how work goes from branch to merge to deploy in carr-system" }),
    Object.freeze({ slug: "enrich-queue", class: "sop", title: "The Enrich Queue — open questions the system chases for you" }),
    Object.freeze({ slug: "fill-it-in-workflow", class: "sop", title: "Fill-It-In Workflow — turning a template into a client deliverable" }),
    Object.freeze({ slug: "finalization-window-relay-briefing", class: "sop", title: "Finalization-Window Relay Briefing" }),
    Object.freeze({ slug: "financing", class: "sop", title: "Financing — Our Playbook (how banks underwrite · how we execute)" }),
    Object.freeze({ slug: "firefly-video-runbook", class: "sop", title: "Firefly Video Pipeline — Runbook (verified end-to-end Jul 7, 2026)" }),
    Object.freeze({ slug: "guided-entry-doctrine", class: "sop", title: "Guided Entry Doctrine — how every Front Door tile runs an entry" }),
    Object.freeze({ slug: "health-audit-task", class: "sop", title: "Monthly health audit — the routine itself" }),
    Object.freeze({ slug: "heartbeat-task", class: "sop", title: "Daily heartbeat — Dell's routine itself" }),
    Object.freeze({ slug: "heavy-build-protocol", class: "sop", title: "Heavy Build Protocol" }),
    Object.freeze({ slug: "idea-resurface-task", class: "sop", title: "Monthly idea-bank resurface — the routine itself" }),
    Object.freeze({ slug: "ingest-tokens-setup", class: "sop", title: "Ingest tokens — the one setup step the three capture lanes are waiting on" }),
    Object.freeze({ slug: "intake-readme", class: "sop", title: "Intake — CARR New Client Questionnaires" }),
    Object.freeze({ slug: "intake-template", class: "sop", title: "New Client Intake: [Prospect Name]" }),
    Object.freeze({ slug: "joe-start-here", class: "sop", title: "JOE, START HERE (your prep for linking Dell's twin brain)" }),
    Object.freeze({ slug: "lease-abstraction-sop", class: "sop", title: "Lease abstraction: the free-read offer, the procedure, and the one-page doctor summary" }),
    Object.freeze({ slug: "legal-considerations-lease-review", class: "sop", title: "Legal Considerations in Healthcare Leases — Agent Reference" }),
    Object.freeze({ slug: "live-boards-readme", class: "sop", title: "live-boards — the current rendered operating surfaces, published for BOTH brains" }),
    Object.freeze({ slug: "local-seo-reference", class: "sop", title: "Local SEO Reference — Four Adapted Audit Prompts" }),
    Object.freeze({ slug: "market-update-nurture-engine-spec", class: "sop", title: "The CARR Market Update, nurture engine spec" }),
    Object.freeze({ slug: "model-tiering", class: "sop", title: "Model tiering — which brain does which work" }),
    Object.freeze({ slug: "monday-brief-task", class: "sop", title: "Monday brief — Dell's routine itself" }),
    Object.freeze({ slug: "negotiation", class: "sop", title: "Negotiation — Our Playbook (posture · landlord mindset · offers & documents)" }),
    Object.freeze({ slug: "neon-database-sop", class: "sop", title: "Neon Database SOP — migrations, roles, backups, branches, and cost on the production Postgres" }),
    Object.freeze({ slug: "network-index", class: "sop", title: "Vendor Network — Index (RETIRED July 7, 2026)" }),
    Object.freeze({ slug: "network-readme", class: "sop", title: "CARR Network Brain — README / Operating Manual" }),
    Object.freeze({ slug: "npi-sweep-sop", class: "sop", title: "NPI Sweep — weekly new-provider detection (SOP)" }),
    Object.freeze({ slug: "pipeline-coo-doctrine", class: "sop", title: "Pipeline COO Doctrine — how Claude keeps the pipeline current on its own" }),
    Object.freeze({ slug: "playbook-review", class: "sop", title: "Playbook Review — the self-improvement loop" }),
    Object.freeze({ slug: "practice-os-playbooks", class: "sop", title: "Practice OS — Vertical Playbooks" }),
    Object.freeze({ slug: "preflight-pass", class: "sop", title: "Pre-Flight Edge-Case Pass — run before any automation goes live" }),
    Object.freeze({ slug: "property-feed-sop", class: "sop", title: "Property Feed — the CREXI listing intake (supply side)" }),
    Object.freeze({ slug: "purchase-vs-lease-fill-guide", class: "sop", title: "Purchase vs. Lease — CARR's Fill & Interpret Methodology" }),
    Object.freeze({ slug: "radar-digest-sop", class: "sop", title: "Radar Weekly Digest — SOP (lane synthesis + scoring)" }),
    Object.freeze({ slug: "renewals", class: "sop", title: "Renewals — Our Playbook (strategy · sourcing · execution · scripts)" }),
    Object.freeze({ slug: "roadmap", class: "sop", title: "AI Workflow Goals — Roadmap" }),
    Object.freeze({ slug: "runbook", class: "sop", title: "Record-Layer Runbook — when something is down" }),
    Object.freeze({ slug: "salesforce-read-sop", class: "sop", title: "Reading Salesforce directly — the SOP" }),
    Object.freeze({ slug: "scale-vision", class: "sop", title: "Scale Vision — what this operation looks like on the way to the top" }),
    Object.freeze({ slug: "scripted-release-pipeline", class: "sop", title: "Scripted release pipeline (Worker + DoctorCRE app)" }),
    Object.freeze({ slug: "session-marker", class: "sop", title: "Active session marker" }),
    Object.freeze({ slug: "session-operating-style", class: "sop", title: "Session operating style — how each brain reports to its human" }),
    Object.freeze({ slug: "shortcut-recipe", class: "sop", title: "The share-sheet Shortcut — build it once on your phone, ~5 minutes" }),
    Object.freeze({ slug: "skills-rule", class: "sop", title: "Skills Standing Rule" }),
    Object.freeze({ slug: "social-publishing-integration", class: "sop", title: "Social Publishing Integration — Tracking" }),
    Object.freeze({ slug: "space-search-runbook", class: "sop", title: "Space-search runbook: either partner pulls the presentation" }),
    Object.freeze({ slug: "space-search-sop", class: "sop", title: "Space Search — the multi-source SOP (supply side, client-driven)" }),
    Object.freeze({ slug: "sprint-system-reference", class: "sop", title: "Sprint-System Reference — Not Built Yet, Read This First When It's Time" }),
    Object.freeze({ slug: "sweep-sop", class: "sop", title: "Sweep SOP — the local pruner's source of truth" }),
    Object.freeze({ slug: "sync-contract", class: "sop", title: "Sync Contract — paired writes and the staleness watch" }),
    Object.freeze({ slug: "system-evolution-plan", class: "sop", title: "System Evolution Plan — the orchestrator migration" }),
    Object.freeze({ slug: "system-report-card-2026-07-07", class: "sop", title: "System Report Card — Baseline Audit (July 7, 2026)" }),
    Object.freeze({ slug: "system-tune-up-sop", class: "sop", title: "System Tune-Up — keeping the CARR AI operating system clean" }),
    Object.freeze({ slug: "template", class: "sop", title: "[Prospect Name]" }),
    Object.freeze({ slug: "tool-contracts-2026-07-30", class: "sop", title: "CARR MCP Tool Contracts — v1" }),
    Object.freeze({ slug: "twin-system-playbook", class: "sop", title: "Dell's Twin System — Transfer Playbook" }),
    Object.freeze({ slug: "voice-profile", class: "sop", title: "Joe's Voice Profile: the personality layer" }),
    Object.freeze({ slug: "work-request-withdrawal", class: "sop", title: "Withdrawing a Work Request captured in error" }),
    Object.freeze({ slug: "workflows", class: "sop", title: "CARR Make.com Automation — Workflow Reference" }),
  ]),
});
