#!/usr/bin/env python3
"""ci-dep-check.py — refuse a tree whose dependencies are unpinned or vulnerable.

WHY. Doctrine is explicit: "Pin dependencies and CI actions; generate an SBOM for
every release" (end-state BDUF, s15 Security/supply chain), and Program 2's gate
names "seeded ... dependency checks" as a class that must independently block.

WHAT WAS ACTUALLY WRONG HERE. Node is fine — mcp-server/package-lock.json exists
and pins transitively. Python was not: requirements.txt declares five packages
with `>=` ranges and there is no lockfile at all, so two installs a week apart
could resolve to different versions and nothing would notice. That is the
reproducibility hole the release manifest's "dependency lock" line assumes is
already closed.

WHY A SEPARATE LOCKFILE RATHER THAN PINNING requirements.txt DIRECTLY. Two
readers with different needs. requirements.txt is the human-facing declaration
and carries environment markers that keep Dell's older runtime installing
correctly (the mypy and pyobjc lines exist for exactly that). Pinning it hard
would make one machine's resolution everyone's constraint. The convention
practitioners already settled on is a loose input and a pinned output —
requirements.in/requirements.txt under pip-tools, here requirements.txt ->
requirements.lock. CI installs the lock; a human installs the txt.

STALENESS IS THE WHOLE POINT OF A LOCK. A lock that silently drifts from its
source is worse than none, so the lock records a hash of the requirements.txt it
was generated from, and this refuses when they disagree. Regenerate with:
    ops/ci-dep-check.py --write-lock

NETWORK. `npm audit` reaches the registry. Offline, it cannot run — and a check
that cannot run reports SKIPPED, never OK (rule 88e9b5eb). Under --strict, which
CI passes, a skip is a failure, because on a runner the network is there and a
skip means the audit quietly stopped happening.
"""

import hashlib
import json
import pathlib
import re
import subprocess
import sys

REPO = pathlib.Path(__file__).resolve().parent.parent
REQ = REPO / "requirements.txt"
LOCK = REPO / "requirements.lock"
NPM_PROJECTS = ["mcp-server", "control-room", "workspace"]
LOCK_HEADER = "# generated by ops/ci-dep-check.py --write-lock; do not hand-edit"
SOURCE_HASH_PREFIX = "# requirements.txt sha256: "


def req_hash() -> str:
    """Hash the MEANINGFUL lines only, so a comment edit does not invalidate
    the lock and train everyone to regenerate it without reading why."""
    lines = []
    for raw in REQ.read_text().splitlines():
        line = raw.split("#", 1)[0].strip()
        if line:
            lines.append(line)
    return hashlib.sha256("\n".join(sorted(lines)).encode()).hexdigest()


def declared_packages():
    """Package names declared in requirements.txt, normalised (PEP 503)."""
    names = []
    for raw in REQ.read_text().splitlines():
        line = raw.split("#", 1)[0].strip()
        if not line:
            continue
        name = re.split(r"[<>=!\[;]", line, maxsplit=1)[0].strip()
        if name:
            names.append(re.sub(r"[-_.]+", "-", name).lower())
    return names


def _norm(name: str) -> str:
    return re.sub(r"[-_.]+", "-", name.split("[")[0]).strip().lower()


def declared_markers():
    """{normalised package name: environment marker} for requirements.txt lines
    that carry one, e.g. pyobjc-framework-EventKit ; sys_platform == "darwin"."""
    out = {}
    for raw in REQ.read_text().splitlines():
        line = raw.split("#", 1)[0].strip()
        if ";" not in line:
            continue
        spec, marker = line.split(";", 1)
        name = _norm(re.split(r"[<>=!\[]", spec, maxsplit=1)[0])
        if name:
            out[name] = marker.strip()
    return out


def platform_marked_packages():
    """Propagate each declared environment marker across the packages that ONLY
    that marked root reaches.

    WHY THIS EXISTS, and it is not a nicety. `pip freeze` emits bare `name==ver`
    and DROPS environment markers, so a lock generated from a Mac silently
    contained pyobjc-core, pyobjc-framework-Cocoa and pyobjc-framework-EventKit
    with no `sys_platform == "darwin"` on them. requirements.txt had the marker
    and the lock did not. The first CI run died trying to build pyobjc-core from
    source on Linux — the lock was Mac-only and nothing said so.

    Reachability, not a name prefix. A package inherits a marker only when EVERY
    root that reaches it carries that same marker; anything an unmarked root also
    needs stays unconditional. That way a shared transitive dependency is never
    accidentally excluded from Linux because a Mac-only package happens to use it
    too.
    """
    try:
        from importlib import metadata
    except ImportError:  # pragma: no cover
        return {}

    requires = {}
    for dist in metadata.distributions():
        name = _norm(dist.metadata["Name"] or "")
        if not name:
            continue
        deps = set()
        for req in dist.requires or []:
            # Skip extras-gated deps; they are not installed unless requested.
            if ";" in req and "extra ==" in req.split(";", 1)[1]:
                continue
            deps.add(_norm(re.split(r"[<>=!;\[\s]", req, maxsplit=1)[0]))
        requires[name] = deps

    def closure(root):
        seen, stack = set(), [root]
        while stack:
            cur = stack.pop()
            for dep in requires.get(cur, ()):
                if dep and dep not in seen:
                    seen.add(dep)
                    stack.append(dep)
        return seen

    markers = declared_markers()
    declared = set(declared_packages())
    unmarked_roots = declared - set(markers)

    # Everything an unmarked root needs must stay unconditional.
    safe = set()
    for root in unmarked_roots:
        safe |= {root} | closure(root)

    marked = {}
    for root, marker in markers.items():
        for pkg in {root} | closure(root):
            if pkg not in safe:
                marked[pkg] = marker
    return marked


def write_lock() -> int:
    freeze = subprocess.run(
        [sys.executable, "-m", "pip", "freeze"],
        capture_output=True, text=True, check=True,
    ).stdout.strip().splitlines()

    marked = platform_marked_packages()
    pinned = []
    for line in freeze:
        if "==" not in line or line.startswith("-e"):
            continue
        marker = marked.get(_norm(line.split("==", 1)[0]))
        pinned.append(f"{line} ; {marker}" if marker else line)
    pinned.sort()
    body = "\n".join([
        LOCK_HEADER,
        "#",
        "# The pinned resolution CI installs. requirements.txt stays the loose,",
        "# human-facing declaration with its environment markers; this is its",
        "# resolved output. Regenerate after changing requirements.txt:",
        "#     ops/ci-dep-check.py --write-lock",
        SOURCE_HASH_PREFIX + req_hash(),
        "",
        *pinned,
        "",
    ])
    LOCK.write_text(body)
    print(f"wrote {LOCK.relative_to(REPO)} — {len(pinned)} pinned package(s)")
    return 0


def check_python(problems, notes):
    if not LOCK.exists():
        problems.append(
            f"{LOCK.relative_to(REPO)} does not exist — Python installs are "
            f"unpinned. Generate it: ops/ci-dep-check.py --write-lock")
        return

    text = LOCK.read_text()
    recorded = None
    for line in text.splitlines():
        if line.startswith(SOURCE_HASH_PREFIX):
            recorded = line[len(SOURCE_HASH_PREFIX):].strip()
            break

    if recorded is None:
        problems.append(f"{LOCK.relative_to(REPO)} records no source hash — cannot tell if it is stale")
    elif recorded != req_hash():
        problems.append(
            f"{LOCK.relative_to(REPO)} is STALE: requirements.txt changed since it "
            f"was generated. Regenerate: ops/ci-dep-check.py --write-lock")

    locked = {}
    for line in text.splitlines():
        if line.startswith("#") or "==" not in line:
            continue
        name, version = line.split("==", 1)
        locked[re.sub(r"[-_.]+", "-", name.split("[")[0]).strip().lower()] = version.strip()

    missing = [p for p in declared_packages() if p not in locked]
    if missing:
        problems.append(
            "declared in requirements.txt but absent from the lock: "
            + ", ".join(sorted(missing))
            + " — the lock was generated from a venv that lacks them")

    unpinned = [l for l in text.splitlines()
                if l.strip() and not l.startswith("#") and "==" not in l]
    if unpinned:
        problems.append(f"{len(unpinned)} unpinned line(s) in the lock")

    if not problems:
        notes.append(f"python: {len(locked)} pinned, lock matches requirements.txt")


def check_npm(problems, notes, skipped, strict):
    for proj in NPM_PROJECTS:
        pkg = REPO / proj / "package.json"
        if not pkg.exists():
            continue
        lock = REPO / proj / "package-lock.json"
        if not lock.exists():
            # A package.json with no dependencies needs no lock; say which case
            # this is rather than failing on an empty project.
            try:
                deps = json.loads(pkg.read_text()).get("dependencies") or {}
            except json.JSONDecodeError:
                deps = {"unparseable": True}
            if deps:
                problems.append(f"{proj}/package-lock.json missing while package.json declares {len(deps)} dependency(ies)")
            else:
                notes.append(f"npm {proj}: no dependencies, no lock needed")
            continue

        res = subprocess.run(
            ["npm", "audit", "--omit=dev", "--audit-level=high", "--json"],
            cwd=REPO / proj, capture_output=True, text=True,
        )
        blob = res.stdout or ""
        if not blob.strip():
            skipped.append(f"npm audit in {proj} produced no report (offline?)")
            continue
        try:
            report = json.loads(blob)
        except json.JSONDecodeError:
            skipped.append(f"npm audit in {proj} returned unparseable output (offline?)")
            continue
        if "error" in report:
            skipped.append(f"npm audit in {proj}: {str(report['error'])[:80]} (offline?)")
            continue

        vulns = (report.get("metadata") or {}).get("vulnerabilities") or {}
        serious = int(vulns.get("high", 0)) + int(vulns.get("critical", 0))
        if serious:
            problems.append(f"npm {proj}: {serious} high/critical advisory(ies)")
        else:
            notes.append(f"npm {proj}: lockfile present, 0 high/critical")


def main() -> int:
    if "--write-lock" in sys.argv:
        return write_lock()

    strict = "--strict" in sys.argv
    problems: list[str] = []
    notes: list[str] = []
    skipped: list[str] = []

    check_python(problems, notes)
    check_npm(problems, notes, skipped, strict)

    for n in notes:
        print(f"  {n}")
    for s in skipped:
        print(f"  SKIPPED: {s}")

    if problems:
        print("\ndependency check failed:", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1

    if skipped and strict:
        print("\ndependency check: SKIPPED work under --strict, which counts as a "
              "failure — on a runner the network is available, so a skip means the "
              "audit stopped running.", file=sys.stderr)
        return 1

    summary = "; ".join(notes) if notes else "nothing to check"
    if skipped:
        summary += f" ({len(skipped)} skipped locally)"
    print(summary)
    return 0


if __name__ == "__main__":
    sys.exit(main())
