#!/usr/bin/env python3
"""Fixtures for ops/migration-safety-gate.py.

The gate holds two promises for every change that reaches main:

1. Each migration the change ADDS carries a rollback note in its header, and
   any destructive or long-locking statement in it is declared in that header
   (expand/contract phase or lock review) rather than discovered in production.
2. db/schema.sql's applied-migration ledger names every migration in the tree
   with the checksum the runner would record, so the reference schema is never
   behind the migrations that define it.

The cases below seed the destructive shapes the gate exists for (dropped
column, narrowed type, NOT NULL without a default on an existing table, a
non-concurrent index) and pin the two ways a check like this gets switched off:
firing on migrations the branch did not add, and passing when it cannot read
its inputs.

Run: .venv/bin/python ops/migration-safety-gate-selftest.py
"""
import hashlib
import importlib.util
import os
import pathlib
import subprocess
import sys
import tempfile
from typing import Any

REPO = pathlib.Path(__file__).resolve().parent.parent
GATE = REPO / "ops" / "migration-safety-gate.py"

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from git_env import fixture_env  # noqa: E402

spec = importlib.util.spec_from_file_location("msg", GATE)
assert spec is not None and spec.loader is not None, f"cannot load {GATE}"
msg: Any = importlib.util.module_from_spec(spec)
sys.modules["msg"] = msg
spec.loader.exec_module(msg)

passed: int = 0
failures: list[str] = []


def check(name: str, cond: object, detail: str = "") -> None:
    global passed
    if cond:
        passed += 1
        print(f"  ok    {name}")
    else:
        failures.append(name)
        print(f"  FAIL  {name}" + (f" — {detail}" if detail else ""))


ROLLBACK = "-- rollback: drop table widget.\n"


def kinds(sql: str) -> list[str]:
    return sorted({f.kind for f in msg.findings(sql)})


# ── header contract ────────────────────────────────────────────────────────
print("header")
check("a migration with no rollback note is refused",
      kinds("create table widget(id int);\n") == ["rollback-missing"],
      repr(kinds("create table widget(id int);\n")))
check("a rollback note passes", kinds(ROLLBACK + "create table widget(id int);\n") == [])
check("forward-only with a reason passes",
      kinds("-- rollback: forward-only — seed rows are append-only history.\n"
            "insert into t values (1);\n") == [])
check("bare forward-only without a reason is refused",
      kinds("-- rollback: forward-only\ninsert into t values (1);\n") == ["rollback-missing"])
check("an empty rollback note is refused",
      kinds("-- rollback:\ninsert into t values (1);\n") == ["rollback-missing"])
check("a rollback note after the first statement is not a header",
      kinds("insert into t values (1);\n-- rollback: delete it.\n") == ["rollback-missing"])
check("the header may follow a generated-file banner",
      kinds("-- GENERATED by ops/scac-mutation-inventory.mjs. Review; never hand-edit.\n"
            + ROLLBACK + "insert into t values (1);\n") == [])

# ── destructive statements ─────────────────────────────────────────────────
print("destructive")
cases = {
    "drop column": "alter table deal drop column legacy_ref;",
    "drop table": "drop table if exists old_thing;",
    "drop schema": "drop schema legacy cascade;",
    "truncate": "truncate commission;",
    "rename column": "alter table deal rename column ref to deal_ref;",
    "rename table": "alter table deal rename to deals;",
    "column type change (narrowing)": "alter table deal alter column notes type varchar(40);",
    "add NOT NULL column without default": "alter table deal add column region text not null;",
    "set NOT NULL on an existing column": "alter table deal alter column region set not null;",
    "delete without where": "delete from commission;",
}
for label, stmt in cases.items():
    got = kinds(ROLLBACK + stmt + "\n")
    check(f"{label} without a marker is refused", got == ["destructive"], repr(got))
    got = kinds(ROLLBACK + "-- expand-contract: contract — readers moved in #1500.\n" + stmt + "\n")
    check(f"{label} with an expand-contract marker passes", got == [], repr(got))

check("a marker without a phase is refused",
      kinds(ROLLBACK + "-- expand-contract: we are sure\nalter table deal drop column x;\n")
      == ["destructive"])
check("NOT NULL with a default is not destructive",
      kinds(ROLLBACK + "alter table deal add column region text not null default 'gulf';\n") == [])
check("NOT NULL on a table created in the same migration is not destructive",
      kinds(ROLLBACK + "create table widget(id int);\n"
            "alter table widget add column name text not null;\n") == [])
check("delete with a where clause is not destructive",
      kinds(ROLLBACK + "delete from commission where id = 1;\n") == [])
check("DROP inside a comment or string is ignored",
      kinds(ROLLBACK + "-- we used to drop table x here\n"
            "comment on table t is 'drop table t; truncate t';\n") == [])
check("drop of a view, function or trigger is not data loss",
      kinds(ROLLBACK + "drop view if exists v_x;\ndrop function if exists f();\n"
            "drop trigger if exists t on deal;\n") == [])
check("a trigger fired by truncate is not a truncate",
      kinds(ROLLBACK + "create trigger guard_truncate before truncate on deal "
            "for each statement execute function guard();\n"
            "create trigger g2 before insert or update or truncate on deal "
            "for each statement execute function guard();\n") == [],
      repr(kinds(ROLLBACK + "create trigger guard_truncate before truncate on deal "
                 "for each statement execute function guard();\n")))
check("granting or revoking the truncate privilege is not a truncate",
      kinds(ROLLBACK + "revoke insert, update, delete, truncate on deal from public;\n"
            "grant truncate on deal to carr_writer;\n") == [])
check("DDL inside a DO block is still seen",
      kinds(ROLLBACK + "do $$ begin alter table deal drop column x; end $$;\n") == ["destructive"])

# ── long locks ─────────────────────────────────────────────────────────────
print("locks")
lock_cases = {
    "non-concurrent index on an existing table": "create index deal_region_ix on deal(region);",
    "validated foreign key on an existing table":
        "alter table deal add constraint deal_party_fk foreign key (party_id) references party(id);",
    "validated check on an existing table":
        "alter table deal add constraint deal_amt_ck check (amount >= 0);",
    "volatile default rewrites the table":
        "alter table deal add column token uuid default gen_random_uuid();",
    "vacuum full": "vacuum full deal;",
    "explicit access exclusive lock": "lock table deal in access exclusive mode;",
}
for label, stmt in lock_cases.items():
    got = kinds(ROLLBACK + stmt + "\n")
    check(f"{label} without review is refused", got == ["long-lock"], repr(got))
    got = kinds(ROLLBACK + "-- lock-review: deal holds under 2k rows; lock is milliseconds.\n"
                + stmt + "\n")
    check(f"{label} with a lock review passes", got == [], repr(got))

check("NOT VALID constraint takes no long lock",
      kinds(ROLLBACK + "alter table deal add constraint deal_amt_ck check (amount >= 0) not valid;\n")
      == [])
check("index on a table created in the same migration is fine",
      kinds(ROLLBACK + "create table widget(id int, name text);\n"
            "create index widget_name_ix on widget(name);\n") == [])
check("a constant default is a fast default",
      kinds(ROLLBACK + "alter table deal add column region text default 'gulf';\n") == [])

# ── ledger coverage ────────────────────────────────────────────────────────
print("ledger")


def ledger(rows: list[tuple[str, str]]) -> str:
    body = "".join(f"{name}\t{digest}\t2026-10-01 00:00:00+00\n" for name, digest in rows)
    return ("CREATE TABLE public.schema_migrations (filename text);\n"
            "COPY public.schema_migrations (filename, sha256, applied_at) FROM stdin;\n"
            + body + "\\.\n")


def digest(text: str) -> str:
    return hashlib.sha256(text.encode()).hexdigest()


a_sql, b_sql = "-- a\n", "-- b\n"
files = {"0001_a.sql": a_sql, "0002_b.sql": b_sql}
problems = msg.ledger_problems(files, ledger([("0001_a.sql", digest(a_sql)),
                                              ("0002_b.sql", digest(b_sql))]))
check("a ledger naming every migration with its checksum passes", problems == [], repr(problems))
problems = msg.ledger_problems(files, ledger([("0001_a.sql", digest(a_sql))]))
check("a migration missing from the ledger is stale",
      problems and "0002_b.sql" in problems[0] and "not in" in problems[0], repr(problems))
problems = msg.ledger_problems(files, ledger([("0001_a.sql", digest(a_sql)),
                                              ("0002_b.sql", digest("-- edited\n"))]))
check("a checksum mismatch is stale", problems and "checksum" in problems[0], repr(problems))
problems = msg.ledger_problems({"0001_a.sql": a_sql},
                               ledger([("0001_a.sql", digest(a_sql)), ("0002_b.sql", "x")]))
check("a ledger row with no file is stale", problems and "no file" in problems[0], repr(problems))
check("a snapshot without a ledger section is refused, never a pass",
      msg.ledger_problems(files, "CREATE TABLE x();\n") != [])

# ── real git trees ─────────────────────────────────────────────────────────
print("git fixtures")
env = fixture_env()
env.update({"GIT_AUTHOR_NAME": "selftest", "GIT_AUTHOR_EMAIL": "selftest@example.invalid",
            "GIT_COMMITTER_NAME": "selftest", "GIT_COMMITTER_EMAIL": "selftest@example.invalid"})


def git(repo: pathlib.Path, *args: str) -> str:
    return subprocess.run(["git", *args], cwd=repo, env=env, check=True,
                          capture_output=True, text=True).stdout


def write(repo: pathlib.Path, name: str, text: str) -> None:
    path = repo / name
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text)


def commit_migration(repo: pathlib.Path, name: str, text: str, *, snapshot: bool = True) -> None:
    write(repo, f"migrations/{name}", text)
    if snapshot:
        rows = [(p.name, digest(p.read_text()))
                for p in sorted((repo / "migrations").glob("*.sql"))]
        write(repo, "db/schema.sql", ledger(rows))
    git(repo, "add", "-A")
    git(repo, "commit", "-q", "-m", name)


def run_gate(repo: pathlib.Path, *args: str) -> subprocess.CompletedProcess:
    gate_env = dict(env)
    gate_env.pop("GITHUB_BASE_REF", None)
    return subprocess.run([sys.executable, str(GATE), "--repo", str(repo), *args],
                          env=gate_env, capture_output=True, text=True)


with tempfile.TemporaryDirectory() as tmp:
    repo = pathlib.Path(tmp) / "r"
    repo.mkdir()
    git(repo, "init", "-q", "-b", "main")
    # Main carries an old, unmarked destructive migration: history the gate
    # must not re-litigate on every branch.
    commit_migration(repo, "0001_legacy.sql", "alter table deal drop column legacy;\n")

    git(repo, "checkout", "-q", "-b", "seeded")
    commit_migration(repo, "0002_drop_region.sql",
                     ROLLBACK + "alter table deal drop column region;\n")
    r = run_gate(repo, "--base", "main")
    out = r.stdout + r.stderr
    check("the seeded destructive migration fails the gate", r.returncode == 1, out)
    check("the refusal names the file and the statement",
          "0002_drop_region.sql" in out and "drop column" in out.lower(), out)
    check("the refusal names the marker that clears it", "expand-contract:" in out, out)
    check("main's own unmarked history is not re-judged", "0001_legacy.sql" not in out, out)

    git(repo, "checkout", "-q", "main")
    git(repo, "checkout", "-q", "-b", "marked")
    commit_migration(repo, "0002_drop_region.sql",
                     ROLLBACK + "-- expand-contract: contract — region readers removed in #1500.\n"
                     "alter table deal drop column region;\n")
    r = run_gate(repo, "--base", "main")
    check("the same migration with its expand-contract marker passes", r.returncode == 0,
          r.stdout + r.stderr)

    git(repo, "checkout", "-q", "main")
    git(repo, "checkout", "-q", "-b", "stale")
    commit_migration(repo, "0002_add.sql", ROLLBACK + "create table widget(id int);\n",
                     snapshot=False)
    r = run_gate(repo, "--base", "main")
    out = r.stdout + r.stderr
    check("a migration added without regenerating db/schema.sql fails", r.returncode == 1, out)
    check("the stale refusal names the migration and the regeneration command",
          "0002_add.sql" in out and "migration-shadow" in out, out)

    git(repo, "checkout", "-q", "main")
    r = run_gate(repo, "--base", "main")
    check("a run on main itself passes", r.returncode == 0, r.stdout + r.stderr)

    r = run_gate(repo, "--base", "no-such-ref")
    check("an unreadable base is exit 2, not a pass", r.returncode == 2, r.stdout + r.stderr)

print(f"\n{passed} passed, {len(failures)} failed")
sys.exit(1 if failures else 0)
