#!/usr/bin/env python3
"""One fail-closed ownership policy for successor recovery and approval checks.

Whole-file ownership requires an exact generated path; SQL additionally must
be new relative to the branch base and carry its generator marker. Mixed files
retain domain bytes and remove only syntactically bounded bookkeeping.
"""
import json
import re


class OwnershipError(ValueError):
    pass


REGISTRY_JS = re.compile(r"mcp-server/src/scac-mutation-registry(?:\.v[1-9][0-9]*)?\.generated\.js\Z")
MIGRATION = re.compile(r"migrations/([0-9]+[a-z]?)_(.+\.sql)\Z")
GENERATED_SQL = re.compile(r"migrations/[0-9]+[a-z]?_.+_(?:scac_successor|registry_seal)\.sql\Z")
JSON_ARTIFACTS = frozenset({
    "ops/config/scac-registry-full-entry-set-seals.json",
    "ops/config/scac-registry-source-inventory-fixtures.v1.json",
})
COUNT_NAMES = r"SCAC_(?:CURRENT_NUMBER|VERSION_COUNT|TOTAL_ENTRY_COUNT|CURRENT_ENTRY_COUNT|CURRENT_SOURCE_COUNT|FULL_SET_SEAL_COUNT)"
ACTIVE_IMPORT = re.compile(r'(?m)^(} from "\./scac-mutation-registry\.v)[1-9][0-9]*(\.generated\.js";)$')


def is_owned_file(path, before, after):
    """Return whole-file ownership. None means absent, never an unreadable blob."""
    if REGISTRY_JS.fullmatch(path):
        return path == "mcp-server/src/scac-mutation-registry.generated.js" or before is None and after is not None
    if path in JSON_ARTIFACTS:
        for content in (before, after):
            if content is not None:
                try:
                    def unambiguous_object(pairs):
                        result = {}
                        for key, value in pairs:
                            if key in result:
                                raise OwnershipError(f"{path}: duplicate generated JSON key {key}")
                            result[key] = value
                        return result
                    value = json.loads(content, object_pairs_hook=unambiguous_object)
                except (ValueError, UnicodeError) as exc:
                    raise OwnershipError(f"{path}: malformed generated JSON") from exc
                if not isinstance(value, dict):
                    raise OwnershipError(f"{path}: generated JSON must be an object")
        return True
    if GENERATED_SQL.fullmatch(path) and before is None and after is not None:
        return bool(re.match(rb"\A-- GENERATED by ops/[A-Za-z0-9_.-]+(?:\. Review; never hand-edit\.)?\r?\n", after))
    return False


# Accept the exact seven-line ledger reader, not arbitrary shell containing a
# registry variable. The error arm has no shell expansion or extra command.
_LEDGER = re.compile(
    r'(?m)^[ \t]*(?P<name>[A-Z][A-Z0-9_]*_REGISTRY_APPLIED)="\$\("\$PSQL" -Atqc \\\n'
    r'  "select exists \(select 1 from schema_migrations where filename=\'[0-9]+[a-z]?_[A-Za-z0-9_]+\.sql\'\)" \\\n'
    r'  2>/dev/null\)"\n'
    r'case "\$(?P=name)" in\n'
    r'  t\|f\) ;;\n'
    r'  \*\) echo "schema-snapshot: [A-Za-z0-9 .,:_-]+" >&2; exit 1 ;;\n'
    r'esac\n'
)
_FRONTIER_ASSIGNMENTS = tuple(re.compile(p) for p in (
    rf'{COUNT_NAMES}=[0-9]+',
    r'SCAC_(?:TOTAL_ENTRY_COUNT|CURRENT_ENTRY_COUNT|CURRENT_SOURCE_COUNT)="\$\("\$PSQL" -Atqc "select (?:coalesce\(sum\(entry_count\),0\)|entry_count|source_entry_count) from ops\.scac_mutation_registry_version where registry_version(?:=\'scac-mutation-registry\.v[0-9]+\'| like \'scac-mutation-registry\.v%\')"\)"',
    r'SCAC_CURRENT_RUNTIME="\$REPO/mcp-server/src/scac-mutation-registry\.v[0-9]+\.generated\.js"',
    r'SCAC_CURRENT_CATALOG_FUNCTION="ops\.scac_mutation_catalog_v[0-9]+_current\(\)"',
    r'SCAC_(?:VERSION_ARRAY|HISTORICAL_ARRAY)="(?:\$SCAC_(?:VERSION_ARRAY|HISTORICAL_ARRAY),)?\'scac-mutation-registry\.v[0-9]+\'(?:,\'scac-mutation-registry\.v[0-9]+\')*"',
))
_FRONTIER_IF = re.compile(r'if \[ "\$[A-Z][A-Z0-9_]*_REGISTRY_APPLIED" = t \]; then')


def _snapshot_domain(text):
    text = _LEDGER.sub("", text)
    lines = text.splitlines(keepends=True)
    def owned_assignment(line):
        return any(pattern.fullmatch(line.strip()) for pattern in _FRONTIER_ASSIGNMENTS)
    # Strip complete pure frontier arms, including their paired fi. An arm
    # containing any domain line remains; its recognized pin lines still own
    # themselves, so arbitrary inserted shell cannot hide in an owned region.
    def arm_end(start):
        depth = 1
        for index in range(start + 1, len(lines)):
            value = lines[index].strip()
            if _FRONTIER_IF.fullmatch(value):
                depth += 1
            elif value == "fi":
                depth -= 1
                if depth == 0:
                    return index
            elif not owned_assignment(lines[index]):
                return None
        return None
    result = []
    index = 0
    while index < len(lines):
        if _FRONTIER_IF.fullmatch(lines[index].strip()):
            end = arm_end(index)
            if end is not None:
                index = end + 1
                continue
        if not owned_assignment(lines[index]):
            result.append(lines[index])
        index += 1
    return "".join(result)



def _inventory_count_tokens(text):
    result = []
    bound = set()
    declaration = re.compile(r"  const (rows|v[0-9]+Rows) = frozenInventory\(REGISTRY_V[0-9]+_VERSION\);")
    count = re.compile(r"(  assert\.equal\()(?P<operand>rows|v[0-9]+Rows|frozenInventory\(REGISTRY_V[0-9]+_VERSION\))(\.length, )([0-9]+)(\);)(\n?)")
    for line in text.splitlines(keepends=True):
        if line.startswith("test("):
            bound.clear()
        declared = declaration.fullmatch(line.rstrip("\n"))
        if declared:
            bound.add(declared[1])
        matched = count.fullmatch(line)
        if matched and (matched["operand"] in bound or matched["operand"].startswith("frozenInventory(")):
            line = matched[1] + matched[2] + matched[3] + "<count>" + matched[5] + matched[6]
        result.append(line)
    return "".join(result)


def domain_bytes(path, content):
    """Project mixed-file bytes without widening ownership to the whole file."""
    if content is None or b"\0" in content:
        return content
    try:
        text = content.decode("utf-8")
    except UnicodeError:
        return content
    if path == "mcp-server/src/mutation-registry.js":
        text = ACTIVE_IMPORT.sub(r'\g<1><number>\2', text)
    elif path == "bin/schema-snapshot.sh":
        text = _snapshot_domain(text)
    elif path == "ops/schema-snapshot-registry-seed-selftest.py":
        text = re.sub(rf'(?m)^(assert "{COUNT_NAMES}=)[0-9]+(" in GENERATOR)$', r'\g<1><count>\2', text)
        text = re.sub(r'(?m)^(assert set\(FULL_SET_SEALS\) == \{f"scac-mutation-registry\.v\{version\}" for version in range\(1, )[0-9]+(\)\})$', r'\g<1><count>\2', text)
    elif path == "mcp-server/test/siep-11-mutation-registry.test.mjs":
        # Only inventory cardinalities, never an arbitrary assertion operand.
        text = _inventory_count_tokens(text)
    return text.encode("utf-8")
