#!/usr/bin/env python3
"""Approval comparison refuses domain changes and unsafe ownership guesses."""
import subprocess
import sys
import unittest

from successor_rehome_test_cases import ROOT, SuccessorCommands


class CheckerCases(SuccessorCommands):
    def check(self, approved, expected):
        result = self.command("successor-only-diff.py", approved, self.head())
        self.assertEqual(result.returncode == 0, expected, result.stdout + result.stderr)
        return result

    def test_main_changes_in_same_file_are_not_branch_patches(self):
        self.write("domain.txt", "before\n" + "context\n" * 12 + "tail\n")
        self.commit("domain.txt")
        self.git("switch", "-q", "main")
        self.git("merge", "-q", "feature")
        self.git("fetch", "-q", "origin")
        self.git("switch", "-q", "feature")
        self.write("domain.txt", "feature\n" + "context\n" * 12 + "tail\n")
        self.commit("domain.txt")
        approved = self.head()
        self.advance_main("domain.txt", "before\n" + "context\n" * 12 + "main tail\n")
        self.git("fetch", "-q", "origin")
        self.git("merge", "-q", "origin/main")
        self.check(approved, True)

    def test_historical_successor_sql_is_domain(self):
        self.git("switch", "-q", "main")
        self.write("migrations/0001_x_scac_successor.sql", "-- GENERATED by ops/scac-mutation-inventory.mjs\nselect 1;\n")
        self.commit("migrations/0001_x_scac_successor.sql")
        self.git("fetch", "-q", "origin")
        self.git("switch", "-q", "feature")
        self.git("merge", "-q", "main")
        self.write("domain.txt", "feature\n")
        self.commit("domain.txt")
        approved = self.head()
        self.write("migrations/0001_x_scac_successor.sql", "-- GENERATED by ops/scac-mutation-inventory.mjs\nselect 2;\n")
        self.commit("migrations/0001_x_scac_successor.sql")
        self.check(approved, False)

    def test_unmarked_sql_is_domain(self):
        self.write("migrations/0002_x_scac_successor.sql", "select 1;\n")
        self.commit("migrations/0002_x_scac_successor.sql")
        approved = self.head()
        self.write("migrations/0002_x_scac_successor.sql", "select 2;\n")
        self.commit("migrations/0002_x_scac_successor.sql")
        self.check(approved, False)

    def test_new_generated_sql_is_owned(self):
        approved = self.head()
        self.write("migrations/0002_x_scac_successor.sql", "-- GENERATED by ops/scac-mutation-inventory.mjs. Review; never hand-edit.\nselect 1;\n")
        self.commit("migrations/0002_x_scac_successor.sql")
        self.check(approved, True)

    def test_binary_mode_and_symlink_changes_refuse(self):
        path = self.repo / "domain.bin"
        path.write_bytes(b"\0before")
        self.commit("domain.bin")
        approved = self.head()
        path.write_bytes(b"\0after")
        self.commit("domain.bin")
        self.check(approved, False)
        approved = self.head()
        self.git("update-index", "--chmod=+x", "domain.bin")
        self.git("commit", "-q", "-m", "Fixture mode")
        self.check(approved, False)

    def test_arbitrary_test_count_is_domain(self):
        target = "mcp-server/test/siep-11-mutation-registry.test.mjs"
        self.write(target, "assert.equal(arbitrary.length, 2);\n")
        self.commit(target)
        approved = self.head()
        self.write(target, "assert.equal(arbitrary.length, 3);\n")
        self.commit(target)
        self.check(approved, False)

    def test_known_count_only_change_is_owned(self):
        target = "ops/schema-snapshot-registry-seed-selftest.py"
        self.write(target, 'assert "SCAC_CURRENT_NUMBER=109" in GENERATOR\nassert domain\n')
        self.commit(target)
        approved = self.head()
        self.write(target, 'assert "SCAC_CURRENT_NUMBER=110" in GENERATOR\nassert domain\n')
        self.commit(target)
        self.check(approved, True)
        approved = self.head()
        self.write(target, 'assert "SCAC_CURRENT_NUMBER=111" in GENERATOR\nassert changed_domain\n')
        self.commit(target)
        self.check(approved, False)

    def test_symlink_in_generated_path_is_domain(self):
        target = "mcp-server/src/scac-mutation-registry.v98.generated.js"
        path = self.repo / target
        path.parent.mkdir(parents=True)
        path.symlink_to("before")
        self.commit(target)
        approved = self.head()
        replacement = path.with_name("replacement")
        replacement.symlink_to("after")
        replacement.replace(path)
        self.commit(target)
        self.check(approved, False)

    def test_duplicate_migration_suffix_refuses(self):
        approved = self.head()
        self.write("migrations/0002_feature.sql", "select 1;\n")
        self.write("migrations/0003_feature.sql", "select 1;\n")
        self.commit("migrations/0002_feature.sql", "migrations/0003_feature.sql")
        result = self.check(approved, False)
        self.assertIn("ambiguous", result.stderr)

    def test_valid_ledger_reader_changes_owned_but_injected_domain_refuses(self):
        target = "bin/schema-snapshot.sh"
        def ledger(number):
            return ('FEATURE_REGISTRY_APPLIED="$("$PSQL" -Atqc \\\n'
                    '  "select exists (select 1 from schema_migrations where filename=\'' + number + '_feature_scac_successor.sql\')" \\\n'
                    '  2>/dev/null)"\n'
                    'case "$FEATURE_REGISTRY_APPLIED" in\n'
                    '  t|f) ;;\n'
                    '  *) echo "schema-snapshot: could not read registry ledger state" >&2; exit 1 ;;\n'
                    'esac\n')
        self.write(target, ledger("0002") + "echo domain\n")
        self.commit(target)
        approved = self.head()
        self.write(target, ledger("0003") + "echo domain\n")
        self.commit(target)
        self.check(approved, True)
        self.write(target, ledger("0003").replace("esac\n", "esac\necho hacked\n") + "echo domain\n")
        self.commit(target)
        self.check(approved, False)

    def test_git_location_environment_is_scrubbed(self):
        self.write("domain.txt", "feature\n")
        self.commit("domain.txt")
        approved = self.head()
        env = dict(self.env, GIT_DIR=str(ROOT / ".git"), GIT_WORK_TREE=str(ROOT))
        result = subprocess.run([sys.executable, str(ROOT / "ops/successor-only-diff.py"), approved, approved], cwd=self.repo, env=env, text=True, capture_output=True)
        self.assertEqual(result.returncode, 0, result.stderr)

    def test_identical_edit_moved_between_functions_refuses(self):
        def source(a, b):
            return f"def function_a():\n    return {a}\n\ndef function_b():\n    return {b}\n"
        self.git("switch", "-q", "main")
        self.write("domain.txt", source(0, 0))
        self.commit("domain.txt")
        self.git("fetch", "-q", "origin")
        self.git("switch", "-q", "feature")
        self.git("merge", "-q", "main")
        self.write("domain.txt", source(1, 0))
        self.commit("domain.txt")
        approved = self.head()
        self.write("domain.txt", source(0, 1))
        self.commit("domain.txt")
        self.check(approved, False)

    def test_historical_generated_runtime_is_domain(self):
        target = "mcp-server/src/scac-mutation-registry.v98.generated.js"
        self.git("switch", "-q", "main")
        self.write(target, "historical generated\n")
        self.commit(target)
        self.git("fetch", "-q", "origin")
        self.git("switch", "-q", "feature")
        self.git("merge", "-q", "main")
        approved = self.head()
        self.write(target, "changed historical\n")
        self.commit(target)
        self.check(approved, False)

    def test_identical_edit_in_long_duplicate_function_bodies_refuses(self):
        padding = "    pass\n" * 8
        def source(a, b):
            return f"def function_a():\n{padding}    return {a}\n{padding}\ndef function_b():\n{padding}    return {b}\n{padding}"
        self.git("switch", "-q", "main")
        self.write("domain.txt", source(0, 0))
        self.commit("domain.txt")
        self.git("fetch", "-q", "origin")
        self.git("switch", "-q", "feature")
        self.git("merge", "-q", "main")
        self.write("domain.txt", source(1, 0))
        self.commit("domain.txt")
        approved = self.head()
        self.write("domain.txt", source(0, 1))
        self.commit("domain.txt")
        self.check(approved, False)

    def test_existing_current_runtime_selector_is_owned(self):
        target = "mcp-server/src/scac-mutation-registry.generated.js"
        self.git("switch", "-q", "main")
        self.write(target, "current selector\n")
        self.commit(target)
        self.git("fetch", "-q", "origin")
        self.git("switch", "-q", "feature")
        self.git("merge", "-q", "main")
        approved = self.head()
        self.write(target, "regenerated selector\n")
        self.commit(target)
        self.check(approved, True)

    def test_generated_json_duplicate_keys_refuse(self):
        target = "ops/config/scac-registry-full-entry-set-seals.json"
        approved = self.head()
        self.write(target, '{"v1":"first","v1":"second"}\n')
        self.commit(target)
        result = self.check(approved, False)
        self.assertIn(target, result.stderr)

    def test_unbound_rows_count_is_domain(self):
        target = "mcp-server/test/siep-11-mutation-registry.test.mjs"
        self.write(target, "  assert.equal(rows.length, 1);\n")
        self.commit(target)
        approved = self.head()
        self.write(target, "  assert.equal(rows.length, 2);\n")
        self.commit(target)
        self.check(approved, False)

    def test_bad_revisions_refuse(self):
        for value in ("--help", "deadbeef", "HEAD"):
            result = self.command("successor-only-diff.py", value, self.head())
            self.assertNotEqual(result.returncode, 0, value)


if __name__ == "__main__":
    names = [name for name in unittest.defaultTestLoader.getTestCaseNames(CheckerCases) if "rehome" not in name and "conflict" not in name]
    suite = unittest.TestSuite(CheckerCases(name) for name in names)
    result = unittest.TextTestRunner(verbosity=2).run(suite)
    sys.exit(0 if result.wasSuccessful() else 1)
