#!/usr/bin/env python3
"""Prove the rehome CLI against the repository schema in disposable Postgres.

Run explicitly with the repository Python. The fast lane uses the smaller CLI
and renderer fixtures; this proof never takes a database URL from its caller.
"""
import json
from pathlib import Path
import re
import shutil
import subprocess
import sys
import tempfile
import unittest

from git_env import fixture_env

ROOT = Path(__file__).resolve().parents[1]


class DisposableRehome(unittest.TestCase):
    def test_regenerated_seal_and_runtime_preserve_main_history(self):
        repo = Path(tempfile.mkdtemp(prefix='successor-postgres-proof-')) / 'repo'
        env = fixture_env()
        def git(*args, cwd=repo):
            return subprocess.check_output(['git', *args], cwd=cwd, env=env, text=True, stderr=subprocess.DEVNULL).strip()
        base = git('rev-parse', 'origin/main', cwd=ROOT)
        git('clone', '--quiet', '--shared', '--no-checkout', str(ROOT), str(repo), cwd=ROOT)
        git('config', 'user.name', 'Fixture')
        git('config', 'user.email', 'fixture@example.invalid')
        git('switch', '-qc', 'main', base)
        # Model this PR delivered on main: the decoder is a source prerequisite,
        # never a bookkeeping rewrite of the caller's generator code.
        shutil.copyfile(ROOT / 'ops/scac-mutation-inventory.mjs', repo / 'ops/scac-mutation-inventory.mjs')
        for path in ('ops/schema-snapshot-registry-seed-selftest.py', 'mcp-server/test/siep-11-mutation-registry.test.mjs'):
            shutil.copyfile(ROOT / path, repo / path)
        git('add', '--', 'ops/scac-mutation-inventory.mjs', 'ops/schema-snapshot-registry-seed-selftest.py', 'mcp-server/test/siep-11-mutation-registry.test.mjs')
        message = repo / '.git/fixture-message'
        message.write_text('Fixture generated-frontier decoder on main\n')
        git('commit', '-q', '-F', str(message))
        git('remote', 'set-url', 'origin', str(repo))
        git('fetch', '-q', 'origin')
        main_seals = json.loads((repo / 'ops/config/scac-registry-full-entry-set-seals.json').read_text())
        numbers = [int(p.name.split('_')[0]) for p in (repo / 'migrations').glob('*.sql') if re.match(r'^\d{4}_', p.name)]
        first = max(numbers)
        version = max(int(k.split('.v')[1]) for k in main_seals) + 1
        historical_runtime = f'mcp-server/src/scac-mutation-registry.v{version-1}.generated.js'
        introduced = git('log', '-1', '--format=%H', 'main', '--', historical_runtime)
        git('switch', '-qc', 'feature', introduced + '^')
        domain = f'migrations/{first:04d}_rehome_fixture_domain.sql'
        seal = f'migrations/{first+1:04d}_rehome_fixture_scac_successor.sql'
        runtime = historical_runtime
        (repo / domain).write_text('create table public.rehome_fixture_domain(id integer);\n')
        (repo / seal).write_text('-- GENERATED by ops/scac-mutation-inventory.mjs. Review; never hand-edit.\nselect 1;\n')
        (repo / runtime).write_text('// Unsealed candidate\n')
        git('add', '--', domain, seal, runtime)
        message = repo / '.git/fixture-message'
        message.write_text('Fixture pending successor\n')
        git('commit', '-q', '-F', str(message))
        approved = git('rev-parse', 'HEAD')
        result = subprocess.run([sys.executable, str(ROOT / 'ops/rehome-successor.py'), str(repo)], cwd=repo,
                                env={**env, 'DATABASE_URL': 'postgres://do-not-use.invalid/shared'},
                                text=True, capture_output=True, timeout=1200)
        self.assertEqual(result.returncode, 0, result.stderr)
        domain = f'migrations/{first+1:04d}_rehome_fixture_domain.sql'
        seal = f'migrations/{first+2:04d}_rehome_fixture_scac_successor.sql'
        runtime = f'mcp-server/src/scac-mutation-registry.v{version}.generated.js'
        receipt = json.loads((repo / '.git/successor-rehome.json').read_text())
        self.assertEqual(receipt['approved_sha'], approved)
        self.assertEqual(receipt['new_sha'], git('rev-parse', 'HEAD'))
        self.assertIn(seal, receipt['rewritten_paths'])
        seals = json.loads((repo / 'ops/config/scac-registry-full-entry-set-seals.json').read_text())
        self.assertEqual({key: seals[key] for key in main_seals}, main_seals)
        self.assertIn(f'scac-mutation-registry.v{version}', seals)
        generated = (repo / seal).read_text()
        self.assertIn('GENERATED by ops/successor_generation.py', generated)
        self.assertIn(f'ops.scac_mutation_catalog_v{version}_current()', generated)
        self.assertIn(f'SCAC_MUTATION_REGISTRY_VERSION = "scac-mutation-registry.v{version}"', (repo / runtime).read_text())
        self.assertIn(f'from "./scac-mutation-registry.v{version}.generated.js";', (repo / 'mcp-server/src/mutation-registry.js').read_text())
        self.assertEqual((repo / historical_runtime).read_bytes(), subprocess.check_output(['git', 'show', 'main:' + historical_runtime], cwd=repo, env=env))
        self.assertEqual((repo / domain).read_text(), 'create table public.rehome_fixture_domain(id integer);\n')
        frontier = subprocess.run(['node', '--input-type=module', '-e',
            "import assert from 'node:assert/strict';import {CURRENT_REGISTRY_VERSION,frozenInventory} from './ops/scac-mutation-inventory.mjs';"
            f"assert.equal(CURRENT_REGISTRY_VERSION,'scac-mutation-registry.v{version}');frozenInventory(CURRENT_REGISTRY_VERSION);"],
            cwd=repo, env=env, capture_output=True, text=True)
        self.assertEqual(frontier.returncode, 0, frontier.stderr)
        modules = repo / 'mcp-server/node_modules'
        modules.symlink_to(ROOT / 'mcp-server/node_modules', target_is_directory=True)
        for command in (
            [sys.executable, 'ops/schema-snapshot-registry-seed-selftest.py'],
            ['node', '--test', 'mcp-server/test/siep-11-mutation-registry.test.mjs'],
        ):
            with self.subTest(command=command):
                checked = subprocess.run(command, cwd=repo, env=env, capture_output=True, text=True, timeout=600)
                self.assertEqual(checked.returncode, 0, checked.stdout[-12000:] + checked.stderr[-6000:])
        seal_file = repo / 'ops/config/scac-registry-full-entry-set-seals.json'
        sealed_bytes = seal_file.read_bytes()
        try:
            seal_file.write_text(json.dumps({key: value for key, value in seals.items()
                if key != f'scac-mutation-registry.v{version}'}))
            missing = subprocess.run([sys.executable, 'ops/schema-snapshot-registry-seed-selftest.py'],
                cwd=repo, env=env, capture_output=True, text=True, timeout=120)
            self.assertNotEqual(missing.returncode, 0, 'missing current seal must fail the snapshot check')
        finally:
            seal_file.write_bytes(sealed_bytes)
        self.assertEqual(git('status', '--porcelain'), '')
        fixture = json.loads((repo / 'ops/config/scac-registry-source-inventory-fixtures.v1.json').read_text())
        main_fixture = json.loads(git('show', 'main:ops/config/scac-registry-source-inventory-fixtures.v1.json'))
        self.assertEqual(fixture['base'], main_fixture['base'])
        self.assertEqual(fixture['patches'][:-1], main_fixture['patches'])


if __name__ == '__main__':
    unittest.main()
