#!/usr/bin/env python3
"""
vault-duplicate-sweep.py — find vault markdown files whose content the doctrine
store already holds, so stale duplicates can be retired without losing anything.

WHY THIS EXISTS. Two vault .md files turned out to be stale copies of live store
documents on 2026-08-09 (linkedin-engagement-engine, social-media-workflow), and a
name-match scan found 193 more candidates. A stale copy of a live doc is worse than
no copy: a session that finds the file cannot tell the store holds something newer,
which is exactly how linkedin-engagement-daily spent three weeks reading a July 20
SOP. Loop #289; procedure fixed by decision 19344749.

WHAT IT COMPARES AGAINST. Backups/portability-mirror/md/<class>/<slug>.md — the
markdown export of the doctrine store, regenerated by the nightly chain. The script
REFUSES to run if that mirror is missing, and warns loudly when it is stale, because
diffing against a stale mirror would call a live file redundant on old evidence.

WHAT IT WILL NOT DO. It does not move, delete or modify anything in report mode,
which is the default. `--stage` moves files, and it moves ONLY files classified
DUPLICATE with zero unresolved inbound pointers. Anything DIVERGENT is never staged
by any mode: the vault copy holds text the store lacks, so staging it would destroy
content. That asymmetry is the whole safety model.

  report (default):  ops/vault-duplicate-sweep.py [--slice PREFIX] [--verbose]
  stage:             ops/vault-duplicate-sweep.py --slice PREFIX --stage
  self-test:         ops/vault-duplicate-sweep.py --selftest
"""

import argparse
import os
import re
import shutil
import subprocess
import sys
import pathlib as _PATHLIB
import time
from datetime import datetime, timezone

# PHASE 4 GATE (2026-08-22). This tool's whole job is the legacy Drive vault, so
# it has no canonical mode: without a Drive root there is nothing for it to look
# at. It used to reach for a hardcoded root with no flag, no reason and no
# refusal, which is the ambient Drive selection Phase 4 exists to remove. Normal
# operation now refuses with the seam named (exit 69, which the nightly chain
# reads as BLOCKED); an acknowledged recovery exercise passes
# --recovery --reason WHY [--vault PATH].
sys.path.insert(0, str(_PATHLIB.Path(__file__).resolve().parents[1]))
from lib.drive_recovery import require_legacy_vault  # noqa: E402

_RECOVERY = require_legacy_vault("record-native duplicate detection (this sweeps the vault's own file tree)")
sys.argv = [sys.argv[0], *_RECOVERY.args]
VAULT = str(_RECOVERY.vault)
# THE MIRROR MOVED HOMES AND THIS POINTER DID NOT FOLLOW. Joe retired the Drive
# vault as the portability mirror's destination on 2026-08-22 and gave it CARR
# OneDrive plus the repo-local copy; this constant kept reading the vault path,
# which stopped being written and then sat there aging. On 2026-08-31 it was 364
# HOURS old and the classifier was still comparing live vault files against it —
# which is how DIVERGENT went from 4 to 86 without the store actually moving.
#
# The REPO-LOCAL copy is the right source for a repo tool: bin/nightly.sh writes
# it every night as the mirror's second destination, it needs no cloud mount, and
# it cannot be silently unmounted the way the previous two homes both were. The
# retired vault path stays as a fallback so an older checkout still finds
# something rather than reporting every file unclassifiable.
_REPO_MIRROR = os.path.join(
    os.path.abspath(os.path.join(os.path.dirname(__file__), "..")), "out/mirror/md")
MIRROR = (_REPO_MIRROR if os.path.isdir(_REPO_MIRROR)
          else os.path.join(VAULT, "Backups/portability-mirror/md"))
CLAUDE_DIR = os.path.expanduser("~/.claude")
# Script-relative, NOT expanduser("~/carr-system"). VAULT and CLAUDE_DIR above
# stay expanduser on purpose — those really are $HOME-relative. REPO is not: on
# a clone outside $HOME it became a directory that does not exist, and since it
# is one of three scan bases the sweep just reported no duplicates in the repo
# half rather than failing.
REPO = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# Directories whose .md files are never candidates.
SKIP_DIRS = {"_to_delete", "Backups", "Graph-System", "node_modules", ".git"}
SKIP_SUFFIXES = (".generations",)

# NEVER stageable, whatever the diff says. These are GENERATED RENDERS or live
# working state that must keep existing as files because something reads the file.
# compiled-rules-* are Dell's boot path until his 2026-08-21 cutoff and are
# dual-exported ON PURPOSE — "fixing" that duplication breaks his sessions.
PROTECTED_STEMS = {
    "compiled-rules-shared", "compiled-rules-joe",
    "open-loops", "open-loops-backlog", "open-loops-closed",
    "decision-history", "decision-history-archive",
    "idea-bank", "team-loops", "action-required",
    "clients-active", "hunt-ledger", "lead-registry",
    "brief-pack", "review-queue", "monday-brief", "monday-brief-task",
    "INDEX", "CLAUDE", "MEMORY", "README",
}

# A paragraph must be at least this long to count as substantial evidence.
MIN_PARA = 140
# Fraction of the vault's substantial paragraphs that must be present in the store
# copy before the file is called a duplicate.
DUP_THRESHOLD = 1.0
# How much of a paragraph to match on (long enough to be distinctive, short enough
# to survive trivial punctuation edits).
PROBE = 110
MIRROR_STALE_HOURS = 36


def norm(t: str) -> str:
    return re.sub(r"\s+", " ", t).strip()


def load_mirror() -> dict:
    """slug -> (path, text) for every store doc in the markdown mirror."""
    if not os.path.isdir(MIRROR):
        sys.exit(f"REFUSING TO RUN: store mirror not found at {MIRROR}\n"
                 "It is generated by the nightly chain. Without it there is nothing "
                 "trustworthy to diff against, and guessing would risk deleting live content.")
    out = {}
    for cls in sorted(os.listdir(MIRROR)):
        d = os.path.join(MIRROR, cls)
        if not os.path.isdir(d):
            continue
        for f in os.listdir(d):
            if f.endswith(".md"):
                p = os.path.join(d, f)
                try:
                    out[f[:-3]] = (p, open(p, encoding="utf-8", errors="replace").read())
                except OSError:
                    pass
    return out


def mirror_age_hours() -> float:
    newest = 0.0
    for root, _, files in os.walk(MIRROR):
        for f in files:
            if f.endswith(".md"):
                try:
                    newest = max(newest, os.path.getmtime(os.path.join(root, f)))
                except OSError:
                    pass
    return (time.time() - newest) / 3600 if newest else 1e9


def vault_candidates(slice_prefix=None):
    for root, dirs, files in os.walk(VAULT):
        dirs[:] = [d for d in dirs
                   if d not in SKIP_DIRS and not d.endswith(SKIP_SUFFIXES)]
        for f in files:
            if not f.endswith(".md"):
                continue
            full = os.path.join(root, f)
            rel = os.path.relpath(full, VAULT)
            if slice_prefix and not rel.startswith(slice_prefix):
                continue
            yield rel, full


def classify(vault_text: str, store_text: str):
    """Return (verdict, coverage, missing_paragraphs)."""
    store_n = norm(store_text)
    paras = [p for p in re.split(r"\n\s*\n", vault_text)
             if len(p.strip()) >= MIN_PARA and not p.strip().startswith("#")]
    if not paras:
        # Nothing substantial to compare. Never call this a duplicate on no evidence.
        return "THIN", 0.0, []
    missing = [p for p in paras if norm(p)[:PROBE] not in store_n]
    coverage = 1.0 - (len(missing) / len(paras))
    verdict = "DUPLICATE" if coverage >= DUP_THRESHOLD else "DIVERGENT"
    return verdict, coverage, missing


POINTER_EXT = (".md", ".py", ".sh", ".mjs", ".js", ".json", ".toml", ".yaml", ".yml", ".txt")
_MD_REF = re.compile(r"([A-Za-z0-9._-]+)\.md")


def build_pointer_index():
    """stem -> {files that mention '<stem>.md'}, built in ONE pass.

    Who still points at a file by NAME is the step that actually breaks routines
    when skipped: a duplicate is harmless until something reads it. This was
    originally a grep per candidate across three trees, which did not finish in
    ten minutes; one indexing pass does the same job in seconds (rule a8c55a47 —
    same job, so it stays one code path rather than a fast one and a slow one).
    """
    # A mention is not a pointer. Session transcripts, tool-result caches, staged
    # exports and generated renders all quote filenames without anything READING
    # them, and counting those made every candidate look pointed-at (190/190 on the
    # first run, which is a useless signal). Only live, hand-authored or executed
    # surfaces count: task and skill definitions, CLAUDE.md, doctrine, repo code.
    NOISE = {"projects", "tool-results", "workflows", "history", "todos",
             "__pycache__", "out", "logs", "scratchpad", "tasks", "shell-snapshots",
             "statsig", "plugins", "ide", "file-history",
             # Added 2026-08-09. A throwaway git worktree is not a live surface by
             # this list's own standard, and .claude/worktrees/ was dominating almost
             # every pointer list — the same 190/190 uselessness the list already
             # exists to prevent, reintroduced by a directory the first pass missed.
             # Each worktree carries a full second copy of corpus/, so one stale
             # checkout could pin a file as "pointed at" forever.
             "worktrees",
             # Added 2026-08-31, loop #289, and it is the SAME finding the line
             # above records rather than a new one — the 2026-08-09 pass named
             # ".claude/worktrees" and stopped there, so three other trees full
             # of second copies kept pinning files. On 2026-08-31 every one of
             # the 98 DUPLICATE rows was held by mirror paths and the stageable
             # set was ZERO, which is the 190/190 uselessness again wearing a
             # different directory name.
             #
             #   .codex-worktrees      Codex's worktrees, one of them inside the
             #                         VAULT itself, each a full second checkout
             #   executor-repos        .claude/executor-repos/<id>/{repo,worktree}
             #   corpus                THE RENDER'S OWN SOURCE. Since the corpus
             #                         flip (2026-08-06) corpus/ under the repo is
             #                         git-canonical and the nightly chain PUSHES
             #                         it out to the vault copy. The corpus twin
             #                         of a vault file is not a pointer to that
             #                         file; it is the same document upstream.
             #   claude-tree           the same relationship for the .claude tree
             ".codex-worktrees", "executor-repos", "corpus", "claude-tree"}
    idx = {}
    for base in (VAULT, CLAUDE_DIR, REPO):
        if not os.path.isdir(base):
            continue
        for root, dirs, files in os.walk(base):
            dirs[:] = [d for d in dirs
                       if d not in SKIP_DIRS and d not in NOISE
                       and not d.endswith(SKIP_SUFFIXES)]
            for f in files:
                if not f.endswith(POINTER_EXT):
                    continue
                full = os.path.join(root, f)
                try:
                    if os.path.getsize(full) > 4_000_000:
                        continue
                    text = open(full, encoding="utf-8", errors="ignore").read()
                except OSError:
                    continue
                rel = os.path.relpath(full, VAULT) if full.startswith(VAULT) else full
                # A mention inside a GENERATED RENDER is not a live pointer either:
                # the render is rebuilt from the store, so the reference dies with
                # the next nightly rather than needing a hand edit.
                if os.path.basename(full)[:-3] in PROTECTED_STEMS or "/briefs/" in full:
                    continue
                for m in set(_MD_REF.findall(text)):
                    idx.setdefault(m, set()).add(rel)
    return idx


def inbound_pointers(stem: str, self_rel: str, idx: dict):
    return sorted(r for r in idx.get(stem, ()) if r != self_rel)


def selftest(mirror):
    """Ground truth: the two files verified by hand on 2026-08-09 must classify
    DUPLICATE. Both now live in _to_delete, so this reads them from there."""
    cases = [
        ("_to_delete/linkedin-queue-and-sop-retired-2026-08-09/linkedin-engagement-engine.md",
         "linkedin-engagement-engine", "DUPLICATE"),
        ("_to_delete/social-media-workflow-store-duplicate-2026-08-09/social-media-workflow.md",
         "social-media-workflow", "DUPLICATE"),
    ]
    ok = True
    for rel, slug, want in cases:
        p = os.path.join(VAULT, rel)
        if not os.path.exists(p) or slug not in mirror:
            print(f"  SKIP  {slug}: fixture missing")
            continue
        v, cov, miss = classify(open(p, encoding="utf-8", errors="replace").read(),
                                mirror[slug][1])
        good = (v == want)
        ok &= good
        print(f"  {'PASS' if good else 'FAIL'}  {slug}: {v} coverage={cov:.1%} "
              f"missing={len(miss)} (want {want})")
    return ok


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--slice", help="only paths starting with this vault-relative prefix")
    ap.add_argument("--stage", action="store_true",
                    help="MOVE DUPLICATE files with no inbound pointers into _to_delete")
    ap.add_argument("--verbose", action="store_true")
    ap.add_argument("--selftest", action="store_true")
    ap.add_argument("--pointers", action="store_true",
                    help="invert the index: list each POINTING file and the store-backed "
                         "files it references, so repointing is planned by edit site "
                         "rather than by target")
    a = ap.parse_args()

    mirror = load_mirror()
    age = mirror_age_hours()
    print(f"store mirror: {len(mirror)} docs, newest {age:.1f}h old")
    if age > MIRROR_STALE_HOURS:
        print(f"  !! MIRROR IS STALE (>{MIRROR_STALE_HOURS}h). A file may look redundant "
              f"only because the mirror predates an edit. Re-run bin/nightly.sh first.")
        if a.stage:
            sys.exit("REFUSING TO STAGE against a stale mirror.")
    print()

    if a.selftest:
        print("SELF-TEST against hand-verified 2026-08-09 cases:")
        sys.exit(0 if selftest(mirror) else 1)

    print("indexing inbound pointers across vault, ~/.claude and the repo ...")
    pidx = build_pointer_index()
    print(f"  indexed {len(pidx)} distinct .md names\n")

    rows, counts = [], {}
    for rel, full in vault_candidates(a.slice):
        stem = os.path.basename(rel)[:-3]
        if stem not in mirror:
            continue
        if stem in PROTECTED_STEMS:
            verdict, cov, miss, ptr = "PROTECTED", 1.0, [], []
        else:
            try:
                vt = open(full, encoding="utf-8", errors="replace").read()
            except OSError:
                continue
            verdict, cov, miss = classify(vt, mirror[stem][1])
            ptr = inbound_pointers(stem, rel, pidx) if verdict == "DUPLICATE" else []
        counts[verdict] = counts.get(verdict, 0) + 1
        rows.append((verdict, rel, cov, len(miss), ptr, miss))

    order = {"DIVERGENT": 0, "DUPLICATE": 1, "THIN": 2, "PROTECTED": 3}
    rows.sort(key=lambda r: (order.get(r[0], 9), r[1]))

    if a.pointers:
        # Plan repointing by EDIT SITE, not by target. 147 pointed-at files can be
        # far fewer places to edit, because one index or runbook often names dozens.
        sites = {}
        for v, rel, _, _, ptr, _ in rows:
            if v != "DUPLICATE":
                continue
            for p in ptr:
                sites.setdefault(p, []).append(os.path.basename(rel)[:-3])
        editable, gated = [], []
        for site, targets in sites.items():
            # A vault .md cannot be edited by any session: record-home-gate.py
            # refuses it (rule 14181e60). Those are loop #287's territory.
            is_vault_md = (not site.startswith("/")) and site.endswith(".md")
            (gated if is_vault_md else editable).append((len(targets), site, targets))
        for label, group in (("EDITABLE", editable), ("GATED (vault .md, cannot edit)", gated)):
            group.sort(reverse=True)
            print(f"\n=== {label}: {len(group)} site(s), "
                  f"{sum(n for n, _, _ in group)} reference(s) ===")
            for n, site, targets in group:
                print(f"  {n:>3}  {site}")
                if a.verbose:
                    print(f"       {', '.join(sorted(targets))}")
        print(f"\ntotal distinct edit sites: {len(sites)}")
        return

    for v, rel, cov, nmiss, ptr, miss in rows:
        if v == "PROTECTED":
            continue
        tag = f"[{v}]"
        extra = ""
        if v == "DUPLICATE":
            extra = "  POINTERS:" + (",".join(ptr) if ptr else "none")
        elif v == "DIVERGENT":
            extra = f"  store is missing {nmiss} para(s)"
        print(f"{tag:<12} {rel}  cov={cov:.0%}{extra}")
        if a.verbose and v == "DIVERGENT":
            for m in miss[:3]:
                print(f"                 MISSING: {norm(m)[:150]}")

    print("\n" + "  ".join(f"{k}={v}" for k, v in sorted(counts.items())))

    stageable = [r for r in rows if r[0] == "DUPLICATE" and not r[4]]
    blocked = [r for r in rows if r[0] == "DUPLICATE" and r[4]]
    print(f"\nstageable now (DUPLICATE, no inbound pointers): {len(stageable)}")
    print(f"DUPLICATE but pointed at (repoint first):        {len(blocked)}")
    print(f"DIVERGENT (merge into store first, NEVER stage): {counts.get('DIVERGENT', 0)}")

    if not a.stage:
        print("\nreport mode; nothing moved. Re-run with --stage --slice <prefix> to move "
              "the stageable set.")
        return

    if not a.slice:
        sys.exit("REFUSING to --stage without --slice. This runs in slices on purpose.")
    dest = os.path.join(VAULT, "_to_delete",
                        f"store-duplicates-{a.slice.strip('/').replace('/', '-').replace(' ', '-')}"
                        f"-{datetime.now(timezone.utc):%Y-%m-%d}")
    os.makedirs(dest, exist_ok=True)
    for _, rel, _, _, _, _ in stageable:
        src = os.path.join(VAULT, rel)
        dst = os.path.join(dest, os.path.basename(rel))
        n = 1
        while os.path.exists(dst):
            dst = os.path.join(dest, f"{os.path.basename(rel)[:-3]}__{n}.md")
            n += 1
        shutil.move(src, dst)
        print(f"  staged  {rel}")
    print(f"\n{len(stageable)} file(s) moved to {os.path.relpath(dest, VAULT)}")
    if blocked:
        print(f"{len(blocked)} left in place because something still points at them.")


if __name__ == "__main__":
    main()
