#!/usr/bin/env python3
"""A worktree never links a shared Python runtime from a different lock.

THE OTHER HALF OF PR #834. That PR proved the npm case:
ops/worktree-runtime-lock-selftest.py drives bin/worktree.sh --plumb against a
canonical tree whose node_modules/.package-lock.json disagrees with the
consuming worktree's package-lock.json, and asserts the symlink is refused. It
did not touch .venv, which every worktree also links out of the canonical tree
and which nothing compared with requirements.lock at all.

WHAT THIS PINS, and both drift directions are recorded costs in this repo:

  stale shared cache   the venv lacks a package the worktree's lock pins, or
                       holds it at a different version. Code that should run
                       does not, and the failure reads as a bug in the branch.

  phantom dependency   the venv holds a distribution the lock does NOT pin, so
                       an import succeeds here and fails in CI, on Dell's
                       machine and in the Worker. requirements.txt's own
                       comments record this happening twice.

FIXTURE TECHNIQUE. A real `pip install` needs the network and would make this
selftest untestable offline and slow. It is not needed: importlib.metadata —
which is what the guard reads — discovers distributions from `*.dist-info`
directories on sys.path. So the fixture builds a `--without-pip` venv (fast,
offline, empty) and writes dist-info directories into its site-packages by
hand. That gives exact control of the installed set, including the cases a real
install could not easily produce on demand (an extra distribution, a single
wrong version).

Run: .venv/bin/python ops/worktree-venv-lock-selftest.py   # exit 0 = all pass
"""

import json
import os
from pathlib import Path
import shutil
import subprocess
import sys
import sysconfig
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from git_env import fixture_env  # noqa: E402


ROOT = Path(__file__).resolve().parents[1]
ZSH = shutil.which("zsh")
assert ZSH, "zsh is required (hosted CI installs it before gate suites)"
FIXTURE_ENV = fixture_env()

# The lock the fixture worktree tracks. Deliberately small, and deliberately
# carries one marker-bearing entry: the guard must treat an entry whose marker
# it cannot evaluate as inapplicable rather than as a mismatch, the same way the
# npm rule treats a platform-inapplicable optional package.
LOCK_TEXT = "\n".join([
    "# generated by ops/ci-dep-check.py --write-lock; do not hand-edit",
    "# requirements.txt sha256: fixture",
    "",
    "alpha==1.0.0",
    "beta==2.0.0",
    "gamma==3.0.0 ; sys_platform == \"fixture-never-matches\"",
    "",
])


def run(*args, cwd, check=True, env=None):
    return subprocess.run(
        args,
        cwd=cwd,
        check=check,
        capture_output=True,
        text=True,
        env=env or FIXTURE_ENV,
    )


def set_installed(venv, packages):
    """Make the fixture venv report exactly `packages` ({name: version})."""
    site = Path(sysconfig.get_path("purelib", vars={
        "base": str(venv), "platbase": str(venv), "installed_base": str(venv),
        "py_version_short": f"{sys.version_info.major}.{sys.version_info.minor}",
        "py_version_nodot": f"{sys.version_info.major}{sys.version_info.minor}",
        "abiflags": sys.abiflags if hasattr(sys, "abiflags") else "",
        "platlibdir": sysconfig.get_config_var("platlibdir") or "lib",
    }))
    if not site.exists():
        # Layouts differ between platforms; find the one this venv actually made.
        candidates = list(venv.glob("lib/python*/site-packages")) \
            + list(venv.glob("Lib/site-packages"))
        assert candidates, f"no site-packages under {venv}"
        site = candidates[0]
    for existing in site.glob("*.dist-info"):
        shutil.rmtree(existing)
    for name, version in packages.items():
        info = site / f"{name}-{version}.dist-info"
        info.mkdir(parents=True)
        (info / "METADATA").write_text(
            f"Metadata-Version: 2.1\nName: {name}\nVersion: {version}\n")
        (info / "INSTALLER").write_text("fixture\n")
    return site


with tempfile.TemporaryDirectory() as td:
    canonical = Path(td) / "canonical"
    canonical.mkdir()
    run("git", "init", "-q", "-b", "main", cwd=canonical)
    run("git", "config", "user.email", "fixture@example.com", cwd=canonical)
    run("git", "config", "user.name", "fixture", cwd=canonical)

    (canonical / "bin").mkdir()
    shutil.copy2(ROOT / "bin" / "worktree.sh", canonical / "bin" / "worktree.sh")
    (canonical / "requirements.lock").write_text(LOCK_TEXT)
    # An mcp-server with a matching runtime, so the npm half of the plumbing
    # stays quiet and every assertion below is about the Python half alone.
    (canonical / "mcp-server").mkdir()
    npm_lock = {
        "name": "fixture", "version": "1.0.0", "lockfileVersion": 3, "requires": True,
        "packages": {
            "": {"name": "fixture", "version": "1.0.0"},
            "node_modules/fixture-pkg": {"version": "1.0.0"},
        },
    }
    (canonical / "mcp-server" / "package.json").write_text(json.dumps(
        {"name": "fixture", "version": "1.0.0"}))
    (canonical / "mcp-server" / "package-lock.json").write_text(json.dumps(npm_lock))
    (canonical / ".gitignore").write_text(".venv/\nout/\nmcp-server/node_modules/\n")
    run("git", "add", "bin/worktree.sh", "requirements.lock", ".gitignore",
        "mcp-server/package.json", "mcp-server/package-lock.json", cwd=canonical)
    run("git", "commit", "-qm", "fixture", cwd=canonical)

    node_runtime = canonical / "mcp-server" / "node_modules"
    node_runtime.mkdir()
    installed_npm = dict(npm_lock)
    installed_npm["packages"] = {"node_modules/fixture-pkg": {"version": "1.0.0"}}
    (node_runtime / ".package-lock.json").write_text(json.dumps(installed_npm))

    venv = canonical / ".venv"
    subprocess.run([sys.executable, "-m", "venv", "--without-pip", str(venv)],
                   check=True, capture_output=True)
    assert (venv / "bin" / "python").exists(), "fixture venv has no bin/python"

    worktree = Path(td) / "worktree"
    run("git", "worktree", "add", "-q", "-b", "fixture-worktree", str(worktree),
        cwd=canonical)
    link_path = worktree / ".venv"

    def plumb(env=None):
        return run(ZSH, str(canonical / "bin" / "worktree.sh"), "--plumb",
                   str(worktree), cwd=worktree, env=env)

    REFUSAL = "does not match this worktree's requirements.lock"

    # CASE 1 — stale shared cache: a package the lock pins is simply absent.
    set_installed(venv, {"alpha": "1.0.0"})
    first = plumb()
    assert REFUSAL in first.stdout, first.stdout
    assert not link_path.exists() and not link_path.is_symlink(), \
        "a venv missing a locked package must not be linked"

    # CASE 2 — exact match links. `pip` is present and is NOT in the lock: the
    # installer bootstrap is never a project dependency and never appears in a
    # `pip freeze` lock, so it must not read as an extra. gamma is absent and
    # must not read as missing: its marker does not apply here.
    set_installed(venv, {"alpha": "1.0.0", "beta": "2.0.0", "pip": "99.0"})
    second = plumb()
    assert link_path.is_symlink(), second.stdout
    assert os.path.realpath(link_path) == os.path.realpath(venv)
    assert "ok  .venv" in second.stdout, second.stdout

    # CASE 3 — the cache drifts AFTER the worktree was plumbed. Re-running the
    # same path must remove the now-unsafe untracked symlink, not leave it
    # trusted. Same third case ops/worktree-runtime-lock-selftest.py pins for npm.
    set_installed(venv, {"alpha": "1.0.0", "beta": "9.9.9"})
    third = plumb()
    assert REFUSAL in third.stdout, third.stdout
    assert not link_path.exists() and not link_path.is_symlink(), \
        "a wrong-version venv must be unlinked, not left trusted"

    # CASE 4 — the phantom dependency: everything the lock pins is installed AND
    # something it does not pin is installed too. That is the direction that
    # makes a local pass a lie about CI, so it refuses like any other drift.
    set_installed(venv, {"alpha": "1.0.0", "beta": "2.0.0", "delta": "0.1.0"})
    fourth = plumb()
    assert REFUSAL in fourth.stdout, fourth.stdout
    assert not link_path.exists() and not link_path.is_symlink(), \
        "a venv holding an unlocked distribution must not be linked"

    # CASE 5 — the escape hatch links, and ANNOUNCES that it did. A machine
    # whose canonical venv has drifted must not lose every worktree's tooling
    # with no way forward; what it must not do is go quiet about it.
    drift_ok = dict(FIXTURE_ENV, CARR_WORKTREE_VENV_DRIFT_OK="1")
    fifth = plumb(env=drift_ok)
    assert "LINKED ANYWAY" in fifth.stdout, fifth.stdout
    assert REFUSAL in fifth.stdout, "the escape hatch must still state the drift"
    assert link_path.is_symlink(), fifth.stdout

    # CASE 6 — the frozen door. --install offers exactly two spellings and
    # neither of them re-resolves: `npm ci`, and pip against requirements.lock.
    # Asserted on --dry-run because the real install needs the network.
    dry = run(ZSH, str(canonical / "bin" / "worktree.sh"), "--install", "--dry-run",
              str(worktree), cwd=worktree)
    assert "npm --prefix" in dry.stdout and " ci" in dry.stdout, dry.stdout
    assert "requirements.lock" in dry.stdout, dry.stdout
    assert "npm install" not in dry.stdout, "the frozen door must never say npm install"
    assert "npm i " not in dry.stdout, "the frozen door must never say npm i"
    assert "requirements.txt" not in dry.stdout, \
        "the frozen door must never install the loose declaration"
    assert "nothing was installed" in dry.stdout, dry.stdout
    assert (worktree / ".venv").is_symlink(), "a dry run must not drop the plumbing"

    # CASE 7 — --install refuses the canonical tree outright. Installing there
    # rewrites the runtime every other worktree on the machine is linked to.
    canon_install = run(ZSH, str(canonical / "bin" / "worktree.sh"), "--install",
                        str(canonical), cwd=canonical, check=False)
    assert canon_install.returncode == 2, canon_install.stdout + canon_install.stderr
    assert "refusing to install into the canonical tree" in canon_install.stdout, \
        canon_install.stdout

print("worktree-venv-lock-selftest: drifted shared .venv refused, frozen door is frozen")
